import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { normalizarNomePessoa } from "@/lib/nome-pessoa";
import { normalizarCpf, validarCpf, validarDataNascimento, validarNomeCompleto } from "@/modules/sorteios/validations/cliente";
import { ErroPortalFotos, carregarSessaoFotos, criarSessaoFotos, exigirTrabalhoCliente, fotoPortalAdmin, limitarPortalFotos, sairPortalFotos } from "./foto-express-portal.server";

export type ResultadoFotos<T> = { ok: true; dados: T } | { ok: false; codigo: string; mensagem: string };
async function executar<T>(fn: () => Promise<T>): Promise<ResultadoFotos<T>> { try { return { ok: true, dados: await fn() }; } catch (e) { if (e instanceof ErroPortalFotos) return { ok: false, codigo: e.codigo, mensagem: e.message }; console.error("[foto-express-portal]", e); return { ok: false, codigo: "ERRO", mensagem: "Não foi possível concluir agora. Tente novamente." }; } }
const digitos = (valor?: string | null) => { let d = (valor ?? "").replace(/\D/g, "").replace(/^0+/, ""); if (d.startsWith("55") && d.length > 11) d = d.slice(2); return d; };
const telefoneConfere = (informado: string, telefone?: string | null, normalizado?: string | null) => { const a = digitos(informado); return a.length >= 10 && (a === digitos(telefone) || a === digitos(normalizado)); };
const esquemaCpf = z.object({ cpf: z.string().trim().min(1).max(20) });
const esquemaTelefone = esquemaCpf.extend({ telefone: z.string().trim().min(8).max(30), lembrar: z.boolean() });
const esquemaCadastro = esquemaTelefone.extend({ nome: z.string().trim().max(200), dataNascimento: z.string().trim().max(10) });

export const iniciarAcessoFotos = createServerFn({ method: "POST" }).inputValidator((v) => esquemaCpf.parse(v)).handler(async ({ data }) => executar(async () => {
  await limitarPortalFotos("cpf"); const cpf = normalizarCpf(data.cpf); if (!cpf || !validarCpf(cpf).ok) throw new ErroPortalFotos("VALIDACAO", "CPF inválido.");
  const admin = await fotoPortalAdmin(); const { data: cliente } = await admin.from("clientes").select("nome,telefone,telefone_normalizado").eq("cpf", cpf).maybeSingle();
  const tel = digitos(cliente?.telefone_normalizado || cliente?.telefone); return { encontrado: !!cliente, nome: cliente?.nome?.trim() || null, telefoneFinal: tel.length >= 4 ? tel.slice(-4) : null };
}));

export const verificarTelefoneFotos = createServerFn({ method: "POST" }).inputValidator((v) => esquemaTelefone.parse(v)).handler(async ({ data }) => executar(async () => {
  await limitarPortalFotos("telefone"); const cpf = normalizarCpf(data.cpf); if (!cpf || !validarCpf(cpf).ok || digitos(data.telefone).length < 10) throw new ErroPortalFotos("VALIDACAO", "Confira o CPF e o telefone.");
  const admin = await fotoPortalAdmin(); const { data: cliente } = await admin.from("clientes").select("*").eq("cpf", cpf).maybeSingle();
  if (!cliente) { const { data: telefoneExistente } = await admin.from("clientes").select("id,cpf").eq("telefone_normalizado", digitos(data.telefone)).limit(1); if (telefoneExistente?.[0]?.cpf) throw new ErroPortalFotos("TELEFONE_EM_USO", "Este telefone já está vinculado a outro cadastro. Procure a loja."); return { etapa: "cadastro" as const }; }
  if (!telefoneConfere(data.telefone, cliente.telefone, cliente.telefone_normalizado)) throw new ErroPortalFotos("DADOS_NAO_CONFEREM", "Os dados não correspondem ao cadastro. Confira o CPF e o telefone.");
  const faltantes: ("nome" | "data_nascimento")[] = []; if (!cliente.nome?.trim()) faltantes.push("nome"); if (!cliente.data_nascimento) faltantes.push("data_nascimento");
  if (faltantes.length) return { etapa: "completar" as const, faltantes };
  await criarSessaoFotos(cliente.id, data.lembrar); return { etapa: "trabalhos" as const };
}));

export const concluirCadastroFotos = createServerFn({ method: "POST" }).inputValidator((v) => esquemaCadastro.parse(v)).handler(async ({ data }) => executar(async () => {
  await limitarPortalFotos("cadastro"); const cpf = normalizarCpf(data.cpf); const telefone = digitos(data.telefone); if (!cpf || !validarCpf(cpf).ok || telefone.length < 10) throw new ErroPortalFotos("VALIDACAO", "Confira o CPF e o telefone.");
  const admin = await fotoPortalAdmin(); const { data: existente } = await admin.from("clientes").select("*").eq("cpf", cpf).maybeSingle(); let clienteId: string;
  if (existente) {
    if (!telefoneConfere(telefone, existente.telefone, existente.telefone_normalizado)) throw new ErroPortalFotos("DADOS_NAO_CONFEREM", "Os dados não correspondem ao cadastro.");
    const atualizacao: { nome?: string; data_nascimento?: string } = {};
    if (!existente.nome?.trim()) { const nome = normalizarNomePessoa(data.nome); const valida = validarNomeCompleto(nome); if (!valida.ok) throw new ErroPortalFotos("VALIDACAO", valida.erro ?? "Nome inválido."); atualizacao.nome = nome; }
    if (!existente.data_nascimento) { const valida = validarDataNascimento(data.dataNascimento); if (!valida.ok) throw new ErroPortalFotos("VALIDACAO", valida.erro ?? "Data inválida."); atualizacao.data_nascimento = data.dataNascimento; }
    if (Object.keys(atualizacao).length) { const { error } = await admin.from("clientes").update(atualizacao).eq("id", existente.id); if (error) throw error; } clienteId = existente.id;
  } else {
    const { data: telefoneExistente } = await admin.from("clientes").select("id,cpf,nome,data_nascimento").eq("telefone_normalizado", telefone).limit(1); const vinculo = telefoneExistente?.[0];
    if (vinculo?.cpf) throw new ErroPortalFotos("TELEFONE_EM_USO", "Este telefone já está vinculado a outro cadastro. Procure a loja.");
    const nome = normalizarNomePessoa(data.nome); const vNome = validarNomeCompleto(nome); const vData = validarDataNascimento(data.dataNascimento); if (!vNome.ok) throw new ErroPortalFotos("VALIDACAO", vNome.erro ?? "Nome inválido."); if (!vData.ok) throw new ErroPortalFotos("VALIDACAO", vData.erro ?? "Data inválida.");
    if (vinculo) { const { error } = await admin.from("clientes").update({ cpf, nome: vinculo.nome || nome, data_nascimento: vinculo.data_nascimento || data.dataNascimento }).eq("id", vinculo.id).is("cpf", null); if (error) throw error; clienteId = vinculo.id; }
    else { const { data: criado, error } = await admin.from("clientes").insert({ cpf, nome, data_nascimento: data.dataNascimento, telefone, telefone_normalizado: telefone }).select("id").single(); if (error || !criado) throw error ?? new Error("Cadastro não criado"); clienteId = criado.id; }
  }
  await criarSessaoFotos(clienteId, data.lembrar); return { etapa: "trabalhos" as const };
}));

export const obterContextoFotos = createServerFn({ method: "GET" }).handler(async () => executar(async () => { const { cliente } = await carregarSessaoFotos(); return { nome: cliente.nome }; }));
export const sairFotos = createServerFn({ method: "POST" }).handler(async () => executar(async () => { await sairPortalFotos(); return { saiu: true }; }));

export const listarTrabalhosFotos = createServerFn({ method: "GET" }).handler(async () => executar(async () => { const { admin, cliente } = await carregarSessaoFotos(); const { data, error } = await admin.from("foto_express_trabalhos").select("id,numero,status,criado_em,atualizado_em,portal_enviado_em,foto_express_itens(count)").eq("cliente_id", cliente.id).eq("origem_portal", true).order("atualizado_em", { ascending: false }); if (error) throw error; return { trabalhos: data ?? [] }; }));
export const criarTrabalhoFotos = createServerFn({ method: "POST" }).inputValidator((v) => z.object({ observacoes: z.string().trim().max(1000).default("") }).parse(v)).handler(async ({ data }) => executar(async () => { const { admin, cliente } = await carregarSessaoFotos(); const { data: trabalho, error } = await admin.from("foto_express_trabalhos").insert({ cliente_id: cliente.id, cliente_nome: cliente.nome, cliente_telefone: cliente.telefone ?? "", observacoes: data.observacoes, origem_portal: true, criado_por: cliente.id }).select("id,numero").single(); if (error || !trabalho) throw error ?? new Error("Trabalho não criado"); return trabalho; }));

export const obterGaleriaFotos = createServerFn({ method: "POST" }).inputValidator((v) => z.object({ trabalhoId: z.string().uuid() }).parse(v)).handler(async ({ data }) => executar(async () => { const { admin, trabalho } = await exigirTrabalhoCliente(data.trabalhoId); const [{ data: formatos }, { data: itens, error }] = await Promise.all([admin.from("foto_express_formatos").select("*").eq("ativo", true).order("ordem").order("nome"), admin.from("foto_express_itens").select("*, arquivo:foto_express_arquivos!foto_express_itens_arquivo_trabalho_fkey(*), formato:foto_express_formatos(*), configuracao:foto_express_configuracoes(*), textos:foto_express_textos(*)").eq("trabalho_id", trabalho.id).order("ordem").order("criado_em")]); if (error) throw error;
  const lista = await Promise.all((itens ?? []).map(async (item) => { const { data: url } = await admin.storage.from(item.arquivo.thumbnail_bucket).createSignedUrl(item.arquivo.thumbnail_path, 3600); return { ...item, thumbnailUrl: url?.signedUrl }; })); return { trabalho, formatos: formatos ?? [], itens: lista };
}));

const idTrabalho = z.object({ trabalhoId: z.string().uuid() });
export const prepararUploadFotos = createServerFn({ method: "POST" }).inputValidator((v) => idTrabalho.extend({ nome: z.string().min(1).max(500), mime: z.enum(["image/jpeg","image/png","image/webp"]) }).parse(v)).handler(async ({ data }) => executar(async () => { await limitarPortalFotos("upload"); const { admin, cliente } = await exigirTrabalhoCliente(data.trabalhoId, true); const id = crypto.randomUUID(); const seguro = data.nome.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-zA-Z0-9._-]/g, "-").slice(-100) || "foto"; const originalPath = `portal/${cliente.id}/${data.trabalhoId}/${id}-${seguro}`; const thumbnailPath = `portal/${cliente.id}/${data.trabalhoId}/${id}.jpg`; const [original, thumb] = await Promise.all([admin.storage.from("foto-express-originais").createSignedUploadUrl(originalPath), admin.storage.from("foto-express-thumbnails").createSignedUploadUrl(thumbnailPath)]); if (original.error || thumb.error || !original.data?.token || !thumb.data?.token) throw new Error("Autorização indisponível"); return { originalPath, thumbnailPath, originalToken: original.data.token, thumbnailToken: thumb.data.token }; }));

export const concluirUploadFotos = createServerFn({ method: "POST" }).inputValidator((v) => idTrabalho.extend({ formatoId: z.string().uuid(), nomeOriginal: z.string().min(1).max(500), mime: z.enum(["image/jpeg","image/png","image/webp"]), tamanho: z.number().int().positive().max(20*1024*1024), largura: z.number().int().positive(), altura: z.number().int().positive(), originalPath: z.string().max(1000), thumbnailPath: z.string().max(1000), ordem: z.number().int().min(0) }).parse(v)).handler(async ({ data }) => executar(async () => { const { admin, cliente } = await exigirTrabalhoCliente(data.trabalhoId, true); const prefixo = `portal/${cliente.id}/${data.trabalhoId}/`; if (!data.originalPath.startsWith(prefixo) || !data.thumbnailPath.startsWith(prefixo)) throw new ErroPortalFotos("VALIDACAO", "Destino do arquivo inválido."); const { data: formato } = await admin.from("foto_express_formatos").select("id").eq("id", data.formatoId).eq("ativo", true).maybeSingle(); if (!formato) throw new ErroPortalFotos("VALIDACAO", "Formato indisponível."); const { data: arquivo, error: erroArquivo } = await admin.from("foto_express_arquivos").insert({ trabalho_id: data.trabalhoId, nome_original: data.nomeOriginal, tipo_mime: data.mime, tamanho_bytes: data.tamanho, largura_px: data.largura, altura_px: data.altura, original_path: data.originalPath, thumbnail_path: data.thumbnailPath, criado_por: cliente.id }).select("id").single(); if (erroArquivo || !arquivo) throw erroArquivo ?? new Error("Arquivo não registrado"); const { data: item, error } = await admin.from("foto_express_itens").insert({ trabalho_id: data.trabalhoId, arquivo_id: arquivo.id, formato_id: data.formatoId, ordem: data.ordem, status_edicao: "CONFIGURADA" }).select("id").single(); if (error || !item) throw error ?? new Error("Foto não registrada"); return item; }));

export const atualizarItensFotos = createServerFn({ method: "POST" }).inputValidator((v) => idTrabalho.extend({ itemIds: z.array(z.string().uuid()).min(1).max(500), formatoId: z.string().uuid().optional(), quantidade: z.number().int().min(1).max(999).optional(), orientacao: z.enum(["AUTOMATICA","RETRATO","PAISAGEM"]).optional() }).parse(v)).handler(async ({ data }) => executar(async () => { const { admin } = await exigirTrabalhoCliente(data.trabalhoId, true); const campos = { ...(data.formatoId ? { formato_id: data.formatoId, status_edicao: "CONFIGURADA" } : {}), ...(data.quantidade ? { quantidade: data.quantidade } : {}), ...(data.orientacao ? { orientacao: data.orientacao } : {}) }; const { error } = await admin.from("foto_express_itens").update(campos).eq("trabalho_id", data.trabalhoId).in("id", data.itemIds); if (error) throw error; return { atualizado: true }; }));

export const duplicarItensFotos = createServerFn({ method: "POST" }).inputValidator((v) => idTrabalho.extend({ itemIds: z.array(z.string().uuid()).min(1).max(100) }).parse(v)).handler(async ({ data }) => executar(async () => { const { admin } = await exigirTrabalhoCliente(data.trabalhoId, true); for (const id of data.itemIds) { const { data: origem } = await admin.from("foto_express_itens").select("*,configuracao:foto_express_configuracoes(*),textos:foto_express_textos(*)").eq("id", id).eq("trabalho_id", data.trabalhoId).maybeSingle(); if (!origem) continue; const { data: novo, error } = await admin.from("foto_express_itens").insert({ trabalho_id: origem.trabalho_id, arquivo_id: origem.arquivo_id, formato_id: origem.formato_id, largura_personalizada_cm: origem.largura_personalizada_cm, altura_personalizada_cm: origem.altura_personalizada_cm, quantidade: origem.quantidade, orientacao: origem.orientacao, ordem: origem.ordem + 1, status_edicao: origem.status_edicao }).select("id").single(); if (error || !novo) throw error; const cfg = Array.isArray(origem.configuracao) ? origem.configuracao[0] : origem.configuracao; if (cfg) await admin.from("foto_express_configuracoes").update({ zoom: cfg.zoom, posicao_x: cfg.posicao_x, posicao_y: cfg.posicao_y, rotacao: cfg.rotacao, crop_x: cfg.crop_x, crop_y: cfg.crop_y, crop_largura: cfg.crop_largura, crop_altura: cfg.crop_altura, espelhar_horizontal: cfg.espelhar_horizontal, espelhar_vertical: cfg.espelhar_vertical, modo_ajuste: cfg.modo_ajuste }).eq("item_id", novo.id); const textos = Array.isArray(origem.textos) ? origem.textos : []; if (textos.length) await admin.from("foto_express_textos").insert(textos.map((t) => ({ item_id: novo.id, conteudo: t.conteudo, posicao_x: t.posicao_x, posicao_y: t.posicao_y, largura_normalizada: t.largura_normalizada, tamanho_normalizado: t.tamanho_normalizado, fonte_id: t.fonte_id, cor: t.cor, alinhamento: t.alinhamento, negrito: t.negrito, italico: t.italico, rotacao: t.rotacao, ordem: t.ordem }))); } return { duplicado: true }; }));

export const excluirItensFotos = createServerFn({ method: "POST" }).inputValidator((v) => idTrabalho.extend({ itemIds: z.array(z.string().uuid()).min(1).max(500) }).parse(v)).handler(async ({ data }) => executar(async () => { const { admin } = await exigirTrabalhoCliente(data.trabalhoId, true); const { data: itens } = await admin.from("foto_express_itens").select("id,arquivo_id").eq("trabalho_id", data.trabalhoId).in("id", data.itemIds); if (!itens?.length) return { excluidos: 0 }; const arquivos = [...new Set(itens.map((i) => i.arquivo_id))]; const { error } = await admin.from("foto_express_itens").delete().eq("trabalho_id", data.trabalhoId).in("id", itens.map((i) => i.id)); if (error) throw error; for (const arquivoId of arquivos) { const { count } = await admin.from("foto_express_itens").select("id", { count: "exact", head: true }).eq("arquivo_id", arquivoId); if (!count) { const { data: arquivo } = await admin.from("foto_express_arquivos").select("original_bucket,original_path,thumbnail_bucket,thumbnail_path").eq("id", arquivoId).maybeSingle(); if (arquivo) { await admin.from("foto_express_arquivos").delete().eq("id", arquivoId); await Promise.all([admin.storage.from(arquivo.original_bucket).remove([arquivo.original_path]), admin.storage.from(arquivo.thumbnail_bucket).remove([arquivo.thumbnail_path])]); } } } return { excluidos: itens.length }; }));

export const obterEditorFotos = createServerFn({ method: "POST" }).inputValidator((v) => idTrabalho.extend({ itemId: z.string().uuid() }).parse(v)).handler(async ({ data }) => executar(async () => { const { admin, trabalho } = await exigirTrabalhoCliente(data.trabalhoId); const [{ data: item, error }, { data: formatos }, { data: navegacao }] = await Promise.all([admin.from("foto_express_itens").select("*,arquivo:foto_express_arquivos!foto_express_itens_arquivo_trabalho_fkey(*),formato:foto_express_formatos(*),configuracao:foto_express_configuracoes(*),textos:foto_express_textos(*)").eq("id", data.itemId).eq("trabalho_id", data.trabalhoId).maybeSingle(), admin.from("foto_express_formatos").select("*").eq("ativo", true).order("ordem"), admin.from("foto_express_itens").select("id").eq("trabalho_id", data.trabalhoId).order("ordem").order("criado_em")]); if (error || !item) throw new ErroPortalFotos("NAO_ENCONTRADO", "Foto não encontrada."); const { data: url } = await admin.storage.from(item.arquivo.original_bucket).createSignedUrl(item.arquivo.original_path, 3600); return { trabalho, item: { ...item, originalUrl: url?.signedUrl }, formatos: formatos ?? [], navegacao: navegacao ?? [] }; }));

const edicao = idTrabalho.extend({ itemId:z.string().uuid(),formatoId:z.string().uuid(),zoom:z.number().min(1).max(5),posicaoX:z.number().min(-1).max(1),posicaoY:z.number().min(-1).max(1),rotacao:z.union([z.literal(0),z.literal(90),z.literal(180),z.literal(270)]),cropX:z.number().min(0).max(1),cropY:z.number().min(0).max(1),cropLargura:z.number().positive().max(1),cropAltura:z.number().positive().max(1),espelharHorizontal:z.boolean(),espelharVertical:z.boolean(),modoAjuste:z.enum(["PREENCHER","AJUSTAR"]),orientacao:z.enum(["AUTOMATICA","RETRATO","PAISAGEM"])});
export const salvarEdicaoFotos = createServerFn({ method:"POST" }).inputValidator((v)=>edicao.parse(v)).handler(async({data})=>executar(async()=>{const {admin}=await exigirTrabalhoCliente(data.trabalhoId,true); const {data:item}=await admin.from("foto_express_itens").select("id").eq("id",data.itemId).eq("trabalho_id",data.trabalhoId).maybeSingle(); if(!item)throw new ErroPortalFotos("NAO_ENCONTRADO","Foto não encontrada."); const {error:e1}=await admin.from("foto_express_configuracoes").update({zoom:data.zoom,posicao_x:data.posicaoX,posicao_y:data.posicaoY,rotacao:data.rotacao,crop_x:data.cropX,crop_y:data.cropY,crop_largura:data.cropLargura,crop_altura:data.cropAltura,espelhar_horizontal:data.espelharHorizontal,espelhar_vertical:data.espelharVertical,modo_ajuste:data.modoAjuste}).eq("item_id",data.itemId); const {error:e2}=await admin.from("foto_express_itens").update({formato_id:data.formatoId,orientacao:data.orientacao,status_edicao:"CONFIGURADA"}).eq("id",data.itemId).eq("trabalho_id",data.trabalhoId); if(e1||e2)throw e1??e2; return{salvo:true};})));

const textoBase=idTrabalho.extend({itemId:z.string().uuid()}); const textoAcao=textoBase.extend({textoId:z.string().uuid()});
export const criarTextoFotos=createServerFn({method:"POST"}).inputValidator((v)=>textoBase.parse(v)).handler(async({data})=>executar(async()=>{const{admin}=await exigirTrabalhoCliente(data.trabalhoId,true);const{data:item}=await admin.from("foto_express_itens").select("id").eq("id",data.itemId).eq("trabalho_id",data.trabalhoId).maybeSingle();if(!item)throw new ErroPortalFotos("NAO_ENCONTRADO","Foto não encontrada.");const{data:texto,error}=await admin.from("foto_express_textos").insert({item_id:data.itemId}).select("*").single();if(error||!texto)throw error;return texto;}));
export const salvarTextoFotos=createServerFn({method:"POST"}).inputValidator((v)=>textoAcao.extend({conteudo:z.string().max(500),posicaoX:z.number().min(0).max(1),posicaoY:z.number().min(0).max(1),larguraNormalizada:z.number().positive().max(1),tamanhoNormalizado:z.number().positive().max(1),fonteId:z.enum(["SANS","SERIF","MONO","DECORATIVA"]),cor:z.string().regex(/^#[0-9A-Fa-f]{6}$/),alinhamento:z.enum(["ESQUERDA","CENTRO","DIREITA"]),negrito:z.boolean(),italico:z.boolean(),rotacao:z.union([z.literal(0),z.literal(90),z.literal(180),z.literal(270)]),versao:z.number().int().positive()}).parse(v)).handler(async({data})=>executar(async()=>{const{admin}=await exigirTrabalhoCliente(data.trabalhoId,true);const{data:texto,error}=await admin.from("foto_express_textos").update({conteudo:data.conteudo,posicao_x:data.posicaoX,posicao_y:data.posicaoY,largura_normalizada:data.larguraNormalizada,tamanho_normalizado:data.tamanhoNormalizado,fonte_id:data.fonteId,cor:data.cor,alinhamento:data.alinhamento,negrito:data.negrito,italico:data.italico,rotacao:data.rotacao,versao:data.versao+1}).eq("id",data.textoId).eq("item_id",data.itemId).eq("versao",data.versao).select("*").maybeSingle();if(error||!texto)throw new ErroPortalFotos("DESATUALIZADO","O texto foi alterado em outra tela.");return texto;}));
export const excluirTextoFotos=createServerFn({method:"POST"}).inputValidator((v)=>textoAcao.parse(v)).handler(async({data})=>executar(async()=>{const{admin}=await exigirTrabalhoCliente(data.trabalhoId,true);await admin.from("foto_express_textos").delete().eq("id",data.textoId).eq("item_id",data.itemId);return{excluido:true};}));
export const duplicarTextoFotos=createServerFn({method:"POST"}).inputValidator((v)=>textoAcao.parse(v)).handler(async({data})=>executar(async()=>{const{admin}=await exigirTrabalhoCliente(data.trabalhoId,true);const{data:t}=await admin.from("foto_express_textos").select("*").eq("id",data.textoId).eq("item_id",data.itemId).maybeSingle();if(!t)throw new ErroPortalFotos("NAO_ENCONTRADO","Texto não encontrado.");const{data:novo,error}=await admin.from("foto_express_textos").insert({item_id:data.itemId,conteudo:t.conteudo,posicao_x:Math.min(1,Number(t.posicao_x)+.03),posicao_y:Math.min(1,Number(t.posicao_y)+.03),largura_normalizada:t.largura_normalizada,tamanho_normalizado:t.tamanho_normalizado,fonte_id:t.fonte_id,cor:t.cor,alinhamento:t.alinhamento,negrito:t.negrito,italico:t.italico,rotacao:t.rotacao,ordem:t.ordem+1}).select("*").single();if(error||!novo)throw error;return novo;}));
export const aplicarTextoTodasFotos=createServerFn({method:"POST"}).inputValidator((v)=>textoAcao.parse(v)).handler(async({data})=>executar(async()=>{const{admin}=await exigirTrabalhoCliente(data.trabalhoId,true);const[{data:t},{data:itens}]=await Promise.all([admin.from("foto_express_textos").select("*").eq("id",data.textoId).eq("item_id",data.itemId).maybeSingle(),admin.from("foto_express_itens").select("id").eq("trabalho_id",data.trabalhoId).neq("id",data.itemId)]);if(!t)throw new ErroPortalFotos("NAO_ENCONTRADO","Texto não encontrado.");if(itens?.length){const{error}=await admin.from("foto_express_textos").insert(itens.map(i=>({item_id:i.id,conteudo:t.conteudo,posicao_x:t.posicao_x,posicao_y:t.posicao_y,largura_normalizada:t.largura_normalizada,tamanho_normalizado:t.tamanho_normalizado,fonte_id:t.fonte_id,cor:t.cor,alinhamento:t.alinhamento,negrito:t.negrito,italico:t.italico,rotacao:t.rotacao,ordem:t.ordem})));if(error)throw error;}return{total:itens?.length??0};}));

export const enviarTrabalhoFotos=createServerFn({method:"POST"}).inputValidator((v)=>idTrabalho.parse(v)).handler(async({data})=>executar(async()=>{await limitarPortalFotos("envio");const{admin,trabalho}=await exigirTrabalhoCliente(data.trabalhoId,true);const{data:itens}=await admin.from("foto_express_itens").select("id,formato_id,status_edicao").eq("trabalho_id",trabalho.id);if(!itens?.length)throw new ErroPortalFotos("VALIDACAO","Adicione pelo menos uma foto.");if(itens.some(i=>!i.formato_id))throw new ErroPortalFotos("VALIDACAO","Escolha o formato de todas as fotos.");const agora=new Date().toISOString();const{error}=await admin.from("foto_express_trabalhos").update({portal_enviado_em:agora,status:"EM_EDICAO",atualizado_em:agora}).eq("id",trabalho.id).is("portal_enviado_em",null);if(error)throw error;return{enviado:true};}));