import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Heart, Image as ImageIcon, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LayoutPortalFotos } from "@/modules/foto-express/portal/LayoutPortalFotos";
import imagemMomentos from "@/assets/foto-portal-momentos.jpg";

export const Route=createFileRoute("/fotos/")({component:LandingFotos,head:()=>({meta:[{title:"Impressão de Fotos | Impressão Digital"},{name:"description",content:"Eternize seus melhores momentos com fotos impressas em alta qualidade, preparadas do seu jeito."},{property:"og:title",content:"Impressão de Fotos | Impressão Digital"},{property:"og:description",content:"Transforme memórias especiais em fotos impressas com qualidade e cuidado."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]})});
function LandingFotos(){return <LayoutPortalFotos><main>
  <section className="relative flex min-h-[min(760px,calc(100dvh-64px))] items-end overflow-hidden bg-foreground">
    <img src={imagemMomentos} alt="Família reunida em uma fotografia impressa" width={1600} height={1000} className="absolute inset-0 h-full w-full object-cover object-[62%_center]"/>
    <div className="absolute inset-0 bg-[linear-gradient(90deg,var(--foto-portal-overlay)_0%,var(--foto-portal-overlay-soft)_55%,transparent_100%)]"/>
    <div className="relative mx-auto w-full max-w-6xl px-4 pb-16 pt-28 sm:px-6 sm:pb-24"><div className="max-w-xl text-primary-foreground"><p className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-widest"><Sparkles className="h-4 w-4"/>Suas memórias merecem sair da tela</p><h1 className="font-serif text-5xl leading-tight sm:text-7xl">Eternize seus momentos</h1><p className="mt-5 max-w-lg text-lg leading-relaxed text-primary-foreground/85 sm:text-xl">Transforme suas fotos favoritas em lembranças para tocar, guardar e compartilhar por muitas gerações.</p><Button asChild size="lg" className="mt-8 h-14 px-7 text-base"><Link to="/fotos/acesso">Quero imprimir minhas fotos<ArrowRight className="ml-2"/></Link></Button></div></div>
  </section>
  <section className="bg-background py-16 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase text-primary">Feito por você</p><h2 className="mt-3 font-serif text-4xl">Do celular para a vida real</h2></div><div className="grid gap-6 sm:grid-cols-3">{[[ImageIcon,"Escolha","Envie suas melhores fotos e selecione o formato."],[Sparkles,"Personalize","Ajuste o enquadramento e acrescente textos."],[Heart,"Receba","Nossa equipe prepara tudo com cuidado para impressão."]].map(([Icone,titulo,texto])=><div key={titulo as string} className="border-t border-border pt-5"><Icone className="h-6 w-6 text-primary"/><h3 className="mt-4 font-semibold">{titulo as string}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{texto as string}</p></div>)}</div></div></div></section>
  <section className="bg-secondary py-14"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-7 px-4 sm:px-6 md:flex-row md:items-center"><div><h2 className="font-serif text-3xl">Qualidade que atravessa o tempo</h2><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm">{["Cores vivas","Formatos variados","Edição fácil"].map(x=><span key={x} className="flex items-center gap-2"><Check className="h-4 w-4 text-primary"/>{x}</span>)}</div></div><Button asChild size="lg"><Link to="/fotos/acesso">Começar agora<ArrowRight className="ml-2"/></Link></Button></div></section>
  </main></LayoutPortalFotos>}