import { FlipHorizontal2, FlipVertical2, Minus, Plus, RotateCcw, RotateCw, Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import type { Formato, Orientacao } from "../types";
import { normalizarRotacao, type EdicaoFoto, type ModoAjuste } from "../lib/transformacaoFoto";

export function ControlesEditor({ edicao, formatoId, formatos, orientacao, somenteLeitura, onChange, onFormato, onOrientacao, onCommit, onReset }: { edicao: EdicaoFoto; formatoId: string; formatos: Formato[]; orientacao: Orientacao; somenteLeitura: boolean; onChange: (v: EdicaoFoto) => void; onFormato: (v: string) => void; onOrientacao: (v: Orientacao) => void; onCommit: () => void; onReset: () => void }) {
  const mudar = (patch: Partial<EdicaoFoto>) => onChange({ ...edicao, ...patch });
  return <div className="space-y-5">
    <div className="space-y-2"><Label>Formato de impressão</Label><Select value={formatoId} disabled={somenteLeitura} onValueChange={onFormato}><SelectTrigger><SelectValue placeholder="Escolha o formato" /></SelectTrigger><SelectContent>{formatos.map((formato) => <SelectItem key={formato.id} value={formato.id}>{formato.nome} · {Number(formato.largura_cm)} × {Number(formato.altura_cm)} cm</SelectItem>)}</SelectContent></Select></div>
    <div className="space-y-2"><Label>Enquadramento</Label><ToggleGroup type="single" variant="outline" value={edicao.modoAjuste} disabled={somenteLeitura} onValueChange={(v: ModoAjuste) => { if (v) { mudar({ modoAjuste: v, posicaoX: 0, posicaoY: 0 }); queueMicrotask(onCommit); } }} className="grid grid-cols-2"><ToggleGroupItem value="PREENCHER">Preencher</ToggleGroupItem><ToggleGroupItem value="AJUSTAR">Ajustar</ToggleGroupItem></ToggleGroup></div>
    <div className="space-y-2"><div className="flex justify-between"><Label>Zoom</Label><span className="text-sm text-muted-foreground">{Math.round(edicao.zoom * 100)}%</span></div><div className="grid grid-cols-[36px_1fr_36px] items-center gap-2"><Button type="button" size="icon" variant="outline" disabled={somenteLeitura || edicao.zoom <= 1} onClick={() => { mudar({ zoom: Math.max(1, edicao.zoom - .1) }); queueMicrotask(onCommit); }} aria-label="Diminuir zoom"><Minus className="h-4 w-4" /></Button><Slider min={1} max={5} step={.01} value={[edicao.zoom]} disabled={somenteLeitura} onValueChange={([v]) => mudar({ zoom: v ?? 1 })} onValueCommit={onCommit} /><Button type="button" size="icon" variant="outline" disabled={somenteLeitura || edicao.zoom >= 5} onClick={() => { mudar({ zoom: Math.min(5, edicao.zoom + .1) }); queueMicrotask(onCommit); }} aria-label="Aumentar zoom"><Plus className="h-4 w-4" /></Button></div></div>
    <div className="space-y-2"><Label>Orientação do formato</Label><Select value={orientacao} disabled={somenteLeitura} onValueChange={(v: Orientacao) => { onOrientacao(v); queueMicrotask(onCommit); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="AUTOMATICA">Automática</SelectItem><SelectItem value="RETRATO">Retrato</SelectItem><SelectItem value="PAISAGEM">Paisagem</SelectItem></SelectContent></Select></div>
    <div className="space-y-2"><Label>Rotação</Label><div className="grid grid-cols-2 gap-2"><Button type="button" variant="outline" disabled={somenteLeitura} onClick={() => { mudar({ rotacao: normalizarRotacao(edicao.rotacao - 90), posicaoX: 0, posicaoY: 0 }); queueMicrotask(onCommit); }}><RotateCcw className="mr-2 h-4 w-4" />Esquerda</Button><Button type="button" variant="outline" disabled={somenteLeitura} onClick={() => { mudar({ rotacao: normalizarRotacao(edicao.rotacao + 90), posicaoX: 0, posicaoY: 0 }); queueMicrotask(onCommit); }}><RotateCw className="mr-2 h-4 w-4" />Direita</Button></div></div>
    <div className="space-y-2"><Label>Espelhamento</Label><div className="grid grid-cols-2 gap-2"><Button type="button" variant={edicao.espelharHorizontal ? "secondary" : "outline"} disabled={somenteLeitura} onClick={() => { mudar({ espelharHorizontal: !edicao.espelharHorizontal }); queueMicrotask(onCommit); }}><FlipHorizontal2 className="mr-2 h-4 w-4" />Horizontal</Button><Button type="button" variant={edicao.espelharVertical ? "secondary" : "outline"} disabled={somenteLeitura} onClick={() => { mudar({ espelharVertical: !edicao.espelharVertical }); queueMicrotask(onCommit); }}><FlipVertical2 className="mr-2 h-4 w-4" />Vertical</Button></div></div>
    <Button type="button" variant="outline" className="w-full" disabled={somenteLeitura} onClick={onReset}><Undo2 className="mr-2 h-4 w-4" />Redefinir</Button>
  </div>;
}