import { ChevronLeft, ChevronRight, FileImage } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ItemGaleria, TextoFoto } from "../types";
import { linhasEntrePecas, type PlanoMontagem } from "../lib/montagem";
import { PecaFoto } from "../components/PecaFoto";

export function PreviewFolha({ plano, indice, onIndice, itens, textos }: { plano: PlanoMontagem; indice: number; onIndice: (i: number) => void; itens: ItemGaleria[]; textos: TextoFoto[] }) {
  const folha = plano.folhas[indice];
  if (!folha) return <div className="flex min-h-80 flex-col items-center justify-center text-muted-foreground"><FileImage className="mb-2 h-10 w-10" /><p>Nenhuma folha montada.</p></div>;
  const proporcao = folha.larguraMm / folha.alturaMm;
  return <div className="space-y-2"><div className="flex items-center justify-between"><Button size="icon" variant="outline" disabled={indice === 0} onClick={() => onIndice(indice - 1)} aria-label="Folha anterior"><ChevronLeft /></Button><span className="text-center text-sm font-medium">Folha {indice + 1} de {plano.folhas.length}{folha.papelNome ? <span className="block text-xs text-muted-foreground">{folha.papelNome} · {folha.larguraMm} × {folha.alturaMm} mm</span> : null}</span><Button size="icon" variant="outline" disabled={indice >= plano.folhas.length - 1} onClick={() => onIndice(indice + 1)} aria-label="Próxima folha"><ChevronRight /></Button></div>
    <div className="mx-auto max-w-full overflow-hidden border bg-background shadow" style={{ aspectRatio: proporcao, width: `min(100%, calc(45dvh * ${proporcao}))` }}>
      <div className="relative h-full w-full">{folha.ocorrencias.map((o) => { const item = itens.find((i) => i.id === o.itemId); if (!item) return null; const girada = o.rotacaoFolha === 90; const larguraFonte = girada ? o.alturaMm : o.larguraMm; const alturaFonte = girada ? o.larguraMm : o.alturaMm; const orientacaoFormato = larguraFonte > alturaFonte ? "PAISAGEM" as const : "RETRATO" as const; return <div key={`${o.itemId}-${o.indiceCopia}`} className="absolute overflow-hidden border border-border" style={{ left: `${o.xMm / folha.larguraMm * 100}%`, top: `${o.yMm / folha.alturaMm * 100}%`, width: `${o.larguraMm / folha.larguraMm * 100}%`, height: `${o.alturaMm / folha.alturaMm * 100}%` }}><div className="absolute left-1/2 top-1/2" style={{ width: girada ? `${o.alturaMm / o.larguraMm * 100}%` : "100%", height: girada ? `${o.larguraMm / o.alturaMm * 100}%` : "100%", transform: `translate(-50%, -50%) rotate(${o.rotacaoFolha}deg)` }}><PecaFoto item={item} textos={textos.filter((t) => t.item_id === item.id)} identificacao={`#${item.ordem + 1} · ${o.indiceCopia}`} orientacaoFormato={orientacaoFormato} /></div></div>; })}{folha.linhaEspacamentoAtiva && linhasEntrePecas(folha).map((linha, i) => <span key={`linha-${i}`} className="pointer-events-none absolute z-20 origin-left" style={{ left: `${linha.x1 / folha.larguraMm * 100}%`, top: `${linha.y1 / folha.alturaMm * 100}%`, width: `${Math.hypot((linha.x2 - linha.x1) / folha.larguraMm, (linha.y2 - linha.y1) / folha.alturaMm) * 100}%`, height: `${Math.max(1, Number(folha.linhaEspessuraMm ?? .2))}px`, backgroundColor: folha.linhaCor, transform: `rotate(${Math.atan2((linha.y2 - linha.y1) / folha.alturaMm, (linha.x2 - linha.x1) / folha.larguraMm) * 180 / Math.PI}deg)` }} />)}</div>
    </div>
  </div>;
}