import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Plus, Ruler } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/AppLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { usePermissoes } from "@/hooks/usePermissoes";
import { useFormatos } from "../hooks/useFotoExpress";
import type { Formato } from "../types";

export function FormatosPagina() {
  const { data = [], isLoading } = useFormatos(true); const qc = useQueryClient(); const [edicao, setEdicao] = useState<Partial<Formato> | null>(null);
  const { user } = useAuth(); const { pode, carregando } = usePermissoes(user?.id); const podeGerenciar = pode("foto_express.formatos.gerenciar");
  const alternar = useMutation({ mutationFn: async (f: Formato) => { const { error } = await supabase.from("foto_express_formatos").update({ ativo: !f.ativo }).eq("id", f.id); if (error) throw error; }, onSuccess: () => void qc.invalidateQueries({ queryKey: ["foto-express", "formatos"] }), onError: (e: Error) => toast.error(e.message) });
  return <><PageHeader titulo="Formatos" subtitulo="Tamanhos disponíveis no FOTO EXPRESS" />{!carregando && podeGerenciar && <div className="mb-4 flex justify-end"><Button onClick={() => setEdicao({ ativo: true, ordem: data.length * 10 + 10 })}><Plus className="mr-2 h-4 w-4" />Novo formato</Button></div>}{isLoading && <p className="text-sm text-muted-foreground">Carregando...</p>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.map((f) => <Card key={f.id}><CardContent className="flex items-center gap-4 p-4"><div className="flex h-12 w-12 items-center justify-center rounded-md bg-accent"><Ruler className="h-6 w-6 text-accent-foreground" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{f.nome}</p>{f.padrao && <Badge variant="secondary">Padrão</Badge>}</div><p className="text-sm text-muted-foreground">{Number(f.largura_cm)} × {Number(f.altura_cm)} cm</p></div>{podeGerenciar && <div className="flex items-center gap-2"><Switch checked={f.ativo} onCheckedChange={() => alternar.mutate(f)} aria-label={`Ativar ${f.nome}`} /><Button variant="outline" size="sm" onClick={() => setEdicao(f)}>Editar</Button></div>}</CardContent></Card>)}</div>{edicao && podeGerenciar && <DialogFormato formato={edicao} onClose={() => setEdicao(null)} onSaved={() => { setEdicao(null); void qc.invalidateQueries({ queryKey: ["foto-express", "formatos"] }); }} />}</>;
}
function DialogFormato({ formato, onClose, onSaved }: { formato: Partial<Formato>; onClose: () => void; onSaved: () => void }) {
  const [nome, setNome] = useState(formato.nome ?? ""); const [largura, setLargura] = useState(String(formato.largura_cm ?? "")); const [altura, setAltura] = useState(String(formato.altura_cm ?? ""));
  const [areaX, setAreaX] = useState(String(Number(formato.area_foto_x ?? 0) * 100)); const [areaY, setAreaY] = useState(String(Number(formato.area_foto_y ?? 0) * 100)); const [areaW, setAreaW] = useState(String(Number(formato.area_foto_largura ?? 1) * 100)); const [areaH, setAreaH] = useState(String(Number(formato.area_foto_altura ?? 1) * 100)); const [corFundo, setCorFundo] = useState(formato.cor_fundo ?? "#FFFFFF");
  const salvar = useMutation({ mutationFn: async () => { const l = Number(largura.replace(",", ".")); const a = Number(altura.replace(",", ".")); const ax = Number(areaX) / 100; const ay = Number(areaY) / 100; const aw = Number(areaW) / 100; const ah = Number(areaH) / 100; if (!nome.trim() || l <= 0 || a <= 0) throw new Error("Informe nome, largura e altura válidos."); if (ax < 0 || ay < 0 || aw <= 0 || ah <= 0 || ax + aw > 1 || ay + ah > 1) throw new Error("A área da foto precisa permanecer dentro do formato."); const campos = { nome: nome.trim(), largura_cm: l, altura_cm: a, codigo: formato.codigo ?? `PERSONALIZADO-${crypto.randomUUID()}`, ordem: formato.ordem ?? 100, area_foto_x: ax, area_foto_y: ay, area_foto_largura: aw, area_foto_altura: ah, cor_fundo: corFundo.toUpperCase() }; const { error } = formato.id ? await supabase.from("foto_express_formatos").update(campos).eq("id", formato.id) : await supabase.from("foto_express_formatos").insert(campos); if (error) throw error; }, onSuccess: () => { toast.success("Formato salvo."); onSaved(); }, onError: (e: Error) => toast.error(e.message) });
  return <Dialog open onOpenChange={(v) => !v && onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{formato.id ? "Editar formato" : "Novo formato"}</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label>Nome</Label><Input value={nome} onChange={(e) => setNome(e.target.value)} /></div><div className="space-y-2"><Label>Largura (cm)</Label><Input inputMode="decimal" value={largura} onChange={(e) => setLargura(e.target.value)} /></div><div className="space-y-2"><Label>Altura (cm)</Label><Input inputMode="decimal" value={altura} onChange={(e) => setAltura(e.target.value)} /></div><div className="sm:col-span-2 border-t pt-4"><p className="font-medium">Área interna da foto</p><p className="text-xs text-muted-foreground">Percentuais relativos à peça completa.</p></div><CampoArea label="Posição X (%)" value={areaX} onChange={setAreaX} /><CampoArea label="Posição Y (%)" value={areaY} onChange={setAreaY} /><CampoArea label="Largura (%)" value={areaW} onChange={setAreaW} /><CampoArea label="Altura (%)" value={areaH} onChange={setAreaH} /><div className="space-y-2 sm:col-span-2"><Label>Cor de fundo</Label><Input type="color" className="h-10" value={corFundo} onChange={(e) => setCorFundo(e.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={() => salvar.mutate()} disabled={salvar.isPending}>Salvar</Button></DialogFooter></DialogContent></Dialog>;
}
function CampoArea({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <div className="space-y-2"><Label>{label}</Label><Input type="number" min={0} max={100} step={0.1} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
