import { useMemo, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CheckSquare, Copy, ImagePlus, Images, Pencil, RotateCw, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/AppLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { excluirItensFotoExpress, limparUploadIncompletoFotoExpress, registrarUploadFotoExpress } from "@/lib/foto-express.functions";
import type { Database } from "@/integrations/supabase/types";
import { criarThumbnail, dimensoesImagem, nomeSeguro, validarImagem } from "../lib/imagens";
import { calcularQualidadeFoto, ROTULO_QUALIDADE } from "../lib/qualidade";
import { useFormatos, useItensGaleria, useTrabalho } from "../hooks/useFotoExpress";
import type { ItemGaleria, Orientacao, Qualidade } from "../types";

const QUALIDADE_ESTILO: Record<Qualidade, string> = { EXCELENTE: "border-emerald-500 text-emerald-700", BOA: "border-sky-500 text-sky-700", BAIXA: "border-amber-500 text-amber-700", MUITO_BAIXA: "border-destructive text-destructive", SEM_FORMATO: "" };
type ItemUpdate = Database["public"]["Tables"]["foto_express_itens"]["Update"];
export function GaleriaPagina({ trabalhoId }: { trabalhoId: string }) {
  const qc = useQueryClient(); const inputRef = useRef<HTMLInputElement>(null); const { data: trabalho } = useTrabalho(trabalhoId); const { data: itens = [], isLoading, isError, error, refetch, isFetching } = useItensGaleria(trabalhoId); const { data: formatos = [] } = useFormatos();
  const registrarUpload = useServerFn(registrarUploadFotoExpress); const limparUploadIncompleto = useServerFn(limparUploadIncompletoFotoExpress); const excluirItens = useServerFn(excluirItensFotoExpress);
  const [selecionados, setSelecionados] = useState<Set<string>>(new Set()); const [enviando, setEnviando] = useState<Record<string, number>>({}); const [arrastando, setArrastando] = useState(false); const [formatoLote, setFormatoLote] = useState(""); const [quantidadeLote, setQuantidadeLote] = useState("1");
  const ids = [...selecionados]; const progresso = useMemo(() => { const valores = Object.values(enviando); return valores.length ? valores.reduce((a, b) => a + b, 0) / valores.length : 0; }, [enviando]);
  const invalidar = () => { void qc.invalidateQueries({ queryKey: ["foto-express", "itens", trabalhoId] }); void qc.invalidateQueries({ queryKey: ["foto-express", "trabalhos"] }); };
  async function enviarArquivos(lista: FileList | File[]) { const arquivos = Array.from(lista); for (const arquivo of arquivos) { let originalPath = ""; let thumbPath = ""; let originalEnviado = false; let limpezaDelegada = false; try { validarImagem(arquivo); setEnviando((p) => ({ ...p, [arquivo.name]: 5 })); const dimensoes = await dimensoesImagem(arquivo); const thumb = await criarThumbnail(arquivo); const id = crypto.randomUUID(); originalPath = `${trabalhoId}/${id}-${nomeSeguro(arquivo.name)}`; thumbPath = `${trabalhoId}/${id}.jpg`; setEnviando((p) => ({ ...p, [arquivo.name]: 25 })); const original = await supabase.storage.from("foto-express-originais").upload(originalPath, arquivo, { contentType: arquivo.type, upsert: false }); if (original.error) throw original.error; originalEnviado = true; setEnviando((p) => ({ ...p, [arquivo.name]: 55 })); const miniatura = await supabase.storage.from("foto-express-thumbnails").upload(thumbPath, thumb, { contentType: "image/jpeg", upsert: false }); if (miniatura.error) { limpezaDelegada = true; const limpeza = await limparUploadIncompleto({ data: { originalPath, thumbnailPath: thumbPath, erro: `Falha ao enviar miniatura: ${miniatura.error.message}` } }); if (limpeza.limpezaPendente) throw new Error(`${miniatura.error.message}. A limpeza ficou pendente.`); throw miniatura.error; } setEnviando((p) => ({ ...p, [arquivo.name]: 75 })); limpezaDelegada = true; await registrarUpload({ data: { trabalhoId, nomeOriginal: arquivo.name, tipoMime: arquivo.type as "image/jpeg" | "image/png" | "image/webp", tamanhoBytes: arquivo.size, larguraPx: dimensoes.largura, alturaPx: dimensoes.altura, originalPath, thumbnailPath: thumbPath, ordem: itens.length + arquivos.indexOf(arquivo) } }); setEnviando((p) => ({ ...p, [arquivo.name]: 100 })); } catch (e) { if (originalEnviado && !limpezaDelegada) { try { await limparUploadIncompleto({ data: { originalPath, thumbnailPath: thumbPath, erro: e instanceof Error ? e.message : "Falha durante o upload" } }); } catch { toast.warning("A limpeza automática do upload não pôde ser confirmada."); } } toast.error(e instanceof Error ? e.message : `Falha ao enviar ${arquivo.name}`); } } setTimeout(() => setEnviando({}), 800); invalidar(); }
  const atualizar = useMutation({ mutationFn: async ({ itemIds, campos }: { itemIds: string[]; campos: ItemUpdate }) => { if (!itemIds.length) throw new Error("Selecione pelo menos uma foto."); const { error } = await supabase.from("foto_express_itens").update(campos).in("id", itemIds); if (error) throw error; }, onSuccess: () => { toast.success("Alterações salvas."); invalidar(); }, onError: (e: Error) => toast.error(e.message) });
  const duplicar = useMutation({ mutationFn: async () => { if (!ids.length) throw new Error("Selecione as fotos para duplicar."); for (const id of ids) { const { error } = await supabase.rpc("foto_express_duplicar_item", { _item_id: id }); if (error) throw error; } }, onSuccess: () => { toast.success("Cópia lógica criada sem repetir o arquivo original."); setSelecionados(new Set()); invalidar(); }, onError: (e: Error) => toast.error(e.message) });
  const excluir = useMutation({ mutationFn: async () => { if (!ids.length) throw new Error("Selecione as fotos para excluir."); if (!window.confirm(`Excluir ${ids.length} foto(s) deste trabalho?`)) return null; return excluirItens({ data: { itemIds: ids } }); }, onSuccess: (resultado) => { if (!resultado) return; if (resultado.limpezasPendentes > 0) toast.warning(`${resultado.itensExcluidos} foto(s) removida(s). A limpeza de ${resultado.limpezasPendentes} arquivo(s) ficou pendente.`); else toast.success("Fotos removidas."); setSelecionados(new Set()); invalidar(); }, onError: (e: Error) => toast.error(e.message) });
  function alternar(id: string) { setSelecionados((atual) => { const novo = new Set(atual); novo.has(id) ? novo.delete(id) : novo.add(id); return novo; }); }
  return <><PageHeader titulo={`Trabalho #${String(trabalho?.numero ?? "").padStart(6, "0")}`} subtitulo={trabalho?.cliente_nome || "Fotos do trabalho"} />
    <div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2"><Button variant="outline" asChild><Link to="/foto-express">Voltar aos trabalhos</Link></Button><Button variant="outline" asChild><Link to="/foto-express/formatos">Formatos</Link></Button></div><Button onClick={() => inputRef.current?.click()}><Upload className="mr-2 h-4 w-4" />Adicionar fotos</Button></div>
    <input ref={inputRef} hidden type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(e) => { if (e.target.files) void enviarArquivos(e.target.files); e.target.value = ""; }} />
    <div onDragEnter={(e) => { e.preventDefault(); setArrastando(true); }} onDragOver={(e) => e.preventDefault()} onDragLeave={() => setArrastando(false)} onDrop={(e) => { e.preventDefault(); setArrastando(false); void enviarArquivos(e.dataTransfer.files); }} className={`mb-4 flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-md border-2 border-dashed p-6 text-center transition-colors ${arrastando ? "border-primary bg-primary/5" : "border-border"}`} onClick={() => inputRef.current?.click()}><ImagePlus className="mb-2 h-8 w-8 text-muted-foreground" /><p className="font-medium">Arraste fotos aqui ou clique para selecionar</p><p className="text-sm text-muted-foreground">JPG, PNG ou WEBP · até 20 MB por arquivo</p></div>
    {Object.keys(enviando).length > 0 && <Card className="mb-4"><CardContent className="space-y-3 p-4"><div className="flex justify-between text-sm font-medium"><span>Enviando {Object.keys(enviando).length} foto(s)</span><span>{Math.round(progresso)}%</span></div><Progress value={progresso} />{Object.entries(enviando).map(([nome, valor]) => <div key={nome} className="grid grid-cols-[1fr_55px] gap-3 text-xs"><span className="truncate">{nome}</span><span className="text-right">{valor}%</span></div>)}</CardContent></Card>}
    {itens.length > 0 && <Card className="mb-4"><CardContent className="space-y-3 p-4"><div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" onClick={() => setSelecionados(selecionados.size === itens.length ? new Set() : new Set(itens.map((i) => i.id)))}><CheckSquare className="mr-2 h-4 w-4" />{selecionados.size === itens.length ? "Desmarcar todas" : "Selecionar todas"}</Button><Button variant="outline" size="sm" onClick={() => duplicar.mutate()} disabled={!ids.length}><Copy className="mr-2 h-4 w-4" />Duplicar</Button><Button variant="outline" size="sm" onClick={() => atualizar.mutate({ itemIds: ids, campos: { orientacao: "PAISAGEM", status_edicao: "CONFIGURADA" } })} disabled={!ids.length}><RotateCw className="mr-2 h-4 w-4" />Paisagem</Button><Button variant="destructive" size="sm" onClick={() => excluir.mutate()} disabled={!ids.length}><Trash2 className="mr-2 h-4 w-4" />Excluir</Button><span className="ml-auto text-sm text-muted-foreground">{ids.length} selecionada(s)</span></div><div className="grid gap-3 md:grid-cols-[1fr_130px_auto]"><Select value={formatoLote} onValueChange={setFormatoLote}><SelectTrigger><SelectValue placeholder="Aplicar formato" /></SelectTrigger><SelectContent>{formatos.map((f) => <SelectItem key={f.id} value={f.id}>{f.nome}</SelectItem>)}</SelectContent></Select><Input type="number" min={1} max={999} value={quantidadeLote} onChange={(e) => setQuantidadeLote(e.target.value)} aria-label="Quantidade" /><Button variant="outline" disabled={!ids.length || (!formatoLote && !quantidadeLote)} onClick={() => atualizar.mutate({ itemIds: ids, campos: { ...(formatoLote ? { formato_id: formatoLote, status_edicao: "CONFIGURADA" } : {}), quantidade: Math.max(1, Number(quantidadeLote) || 1) } })}>Aplicar às selecionadas</Button></div></CardContent></Card>}
    {isLoading && <p className="text-sm text-muted-foreground">Carregando galeria...</p>}
    {!isLoading && isError && <Card><CardContent className="flex flex-col items-center gap-3 p-12 text-center"><Images className="h-10 w-10 text-destructive" /><div><p className="font-semibold">Não foi possível carregar a galeria</p><p className="text-sm text-muted-foreground">{error instanceof Error ? error.message : "Ocorreu um erro ao buscar as fotos deste trabalho."}</p></div><Button variant="outline" onClick={() => void refetch()} disabled={isFetching}>{isFetching ? "Tentando novamente..." : "Tentar novamente"}</Button></CardContent></Card>}
    {!isLoading && !isError && itens.length === 0 && <Card><CardContent className="flex flex-col items-center p-12 text-center"><Images className="mb-3 h-10 w-10 text-muted-foreground" /><p className="font-semibold">Nenhuma foto neste trabalho</p><p className="text-sm text-muted-foreground">Envie as primeiras imagens para começar.</p></CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{itens.map((item) => <FotoCard key={item.id} item={item} selecionado={selecionados.has(item.id)} formatos={formatos} onAlternar={() => alternar(item.id)} onSalvar={(campos) => atualizar.mutate({ itemIds: [item.id], campos })} />)}</div>
  </>;
}
function FotoCard({ item, selecionado, formatos, onAlternar, onSalvar }: { item: ItemGaleria; selecionado: boolean; formatos: ReturnType<typeof useFormatos>["data"]; onAlternar: () => void; onSalvar: (campos: ItemUpdate) => void }) {
  const largura = item.largura_personalizada_cm ?? item.formato?.largura_cm; const altura = item.altura_personalizada_cm ?? item.formato?.altura_cm; const resultado = calcularQualidadeFoto({ larguraPx: item.arquivo.largura_px, alturaPx: item.arquivo.altura_px, larguraCm: largura ? Number(largura) : null, alturaCm: altura ? Number(altura) : null, orientacao: item.orientacao });
  return <Card className={selecionado ? "ring-2 ring-primary" : ""}><CardContent className="space-y-3 p-3"><div className="relative aspect-[4/3] w-full overflow-hidden rounded-md bg-muted">{item.thumbnailUrl ? <img src={item.thumbnailUrl} alt={item.arquivo.nome_original} className="h-full w-full object-cover" /> : <Images className="absolute left-1/2 top-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-muted-foreground" />}<span className="absolute left-2 top-2 rounded bg-background/90 p-1"><Checkbox checked={selecionado} onCheckedChange={onAlternar} aria-label={`Selecionar ${item.arquivo.nome_original}`} /></span></div><div><p className="truncate text-sm font-semibold" title={item.arquivo.nome_original}>{item.arquivo.nome_original}</p><p className="text-xs text-muted-foreground">{item.arquivo.largura_px} × {item.arquivo.altura_px} px</p></div><Badge variant="outline" className={QUALIDADE_ESTILO[resultado.qualidade]}>{ROTULO_QUALIDADE[resultado.qualidade]}{resultado.dpi ? ` · ${resultado.dpi} DPI` : ""}</Badge><Button variant="outline" className="w-full" asChild><Link to="/foto-express/$trabalhoId/fotos/$itemId/editar" params={{ trabalhoId: item.trabalho_id, itemId: item.id }}><Pencil className="mr-2 h-4 w-4" />Editar</Link></Button><div className="grid gap-2"><Select value={item.formato_id ?? "SEM"} onValueChange={(v) => onSalvar({ formato_id: v === "SEM" ? null : v, status_edicao: v === "SEM" ? "NAO_CONFIGURADA" : "CONFIGURADA" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="SEM">Sem formato</SelectItem>{(formatos ?? []).map((f) => <SelectItem key={f.id} value={f.id}>{f.nome}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-2 gap-2"><div><Label className="text-xs">Cópias</Label><Input type="number" min={1} max={999} defaultValue={item.quantidade} onBlur={(e) => onSalvar({ quantidade: Math.max(1, Number(e.target.value) || 1) })} /></div><div><Label className="text-xs">Orientação</Label><Select value={item.orientacao} onValueChange={(v: Orientacao) => onSalvar({ orientacao: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="AUTOMATICA">Automática</SelectItem><SelectItem value="RETRATO">Retrato</SelectItem><SelectItem value="PAISAGEM">Paisagem</SelectItem></SelectContent></Select></div></div></div></CardContent></Card>;
}
