/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as CurriculosIndexRouteImport } from './routes/curriculos.index'
import { Route as CurriculosIdRouteImport } from './routes/curriculos.$id'
import { Route as OrcamentoTokenRouteImport } from './routes/orcamento.$token'
import { Route as CurriculoPublicoTokenRouteImport } from './routes/curriculo.publico.$token'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculosIndexRoute = CurriculosIndexRouteImport.update({
  id: '/curriculos/',
  path: '/curriculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculosIdRoute = CurriculosIdRouteImport.update({
  id: '/curriculos/$id',
  path: '/curriculos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoTokenRoute = OrcamentoTokenRouteImport.update({
  id: '/orcamento/$token',
  path: '/orcamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoPublicoTokenRoute = CurriculoPublicoTokenRouteImport.update({
  id: '/curriculo/publico/$token',
  path: '/curriculo/publico/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/precos': typeof PrecosRoute
  '/whatsapp': typeof WhatsappRoute
  '/curriculos/$id': typeof CurriculosIdRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/curriculos/': typeof CurriculosIndexRoute
  '/curriculo/publico/$token': typeof CurriculoPublicoTokenRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/precos': typeof PrecosRoute
  '/whatsapp': typeof WhatsappRoute
  '/curriculos/$id': typeof CurriculosIdRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/curriculos': typeof CurriculosIndexRoute
  '/curriculo/publico/$token': typeof CurriculoPublicoTokenRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/precos': typeof PrecosRoute
  '/whatsapp': typeof WhatsappRoute
  '/curriculos/$id': typeof CurriculosIdRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/curriculos/': typeof CurriculosIndexRoute
  '/curriculo/publico/$token': typeof CurriculoPublicoTokenRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/orcamentos'
    | '/precos'
    | '/whatsapp'
    | '/curriculos/$id'
    | '/orcamento/$token'
    | '/curriculos/'
    | '/curriculo/publico/$token'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/orcamentos'
    | '/precos'
    | '/whatsapp'
    | '/curriculos/$id'
    | '/orcamento/$token'
    | '/curriculos'
    | '/curriculo/publico/$token'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/orcamentos'
    | '/precos'
    | '/whatsapp'
    | '/curriculos/$id'
    | '/orcamento/$token'
    | '/curriculos/'
    | '/curriculo/publico/$token'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  HistoricoRoute: typeof HistoricoRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PrecosRoute: typeof PrecosRoute
  WhatsappRoute: typeof WhatsappRoute
  CurriculosIdRoute: typeof CurriculosIdRoute
  OrcamentoTokenRoute: typeof OrcamentoTokenRoute
  CurriculosIndexRoute: typeof CurriculosIndexRoute
  CurriculoPublicoTokenRoute: typeof CurriculoPublicoTokenRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculos/': {
      id: '/curriculos/'
      path: '/curriculos'
      fullPath: '/curriculos/'
      preLoaderRoute: typeof CurriculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculos/$id': {
      id: '/curriculos/$id'
      path: '/curriculos/$id'
      fullPath: '/curriculos/$id'
      preLoaderRoute: typeof CurriculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento/$token': {
      id: '/orcamento/$token'
      path: '/orcamento/$token'
      fullPath: '/orcamento/$token'
      preLoaderRoute: typeof OrcamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo/publico/$token': {
      id: '/curriculo/publico/$token'
      path: '/curriculo/publico/$token'
      fullPath: '/curriculo/publico/$token'
      preLoaderRoute: typeof CurriculoPublicoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  HistoricoRoute: HistoricoRoute,
  OrcamentosRoute: OrcamentosRoute,
  PrecosRoute: PrecosRoute,
  WhatsappRoute: WhatsappRoute,
  CurriculosIdRoute: CurriculosIdRoute,
  OrcamentoTokenRoute: OrcamentoTokenRoute,
  CurriculosIndexRoute: CurriculosIndexRoute,
  CurriculoPublicoTokenRoute: CurriculoPublicoTokenRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
