/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BotRouteImport } from './routes/bot'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MelhoriasRouteImport } from './routes/melhorias'
import { Route as MensagensRapidasRouteImport } from './routes/mensagens-rapidas'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as CurriculosIndexRouteImport } from './routes/curriculos.index'
import { Route as CurriculosIdRouteImport } from './routes/curriculos.$id'
import { Route as OrcamentoTokenRouteImport } from './routes/orcamento.$token'
import { Route as SorteiosPublicoIndexRouteImport } from './routes/sorteios-publico.index'
import { Route as SorteiosPublicoCadastroRouteImport } from './routes/sorteios-publico.cadastro'
import { Route as SorteiosPublicoCuponsRouteImport } from './routes/sorteios-publico.cupons'
import { Route as SorteiosPublicoInformacoesRouteImport } from './routes/sorteios-publico.informacoes'
import { Route as SorteiosPublicoNotasRouteImport } from './routes/sorteios-publico.notas'
import { Route as SorteiosPublicoPainelRouteImport } from './routes/sorteios-publico.painel'
import { Route as SorteiosPublicoTelefoneRouteImport } from './routes/sorteios-publico.telefone'
import { Route as SorteiosPublicoTermosRouteImport } from './routes/sorteios-publico.termos'
import { Route as SorteiosIndexRouteImport } from './routes/sorteios.index'
import { Route as SorteiosNovoRouteImport } from './routes/sorteios.novo'
import { Route as CurriculoPublicoTokenRouteImport } from './routes/curriculo.publico.$token'
import { Route as SorteiosIdIndexRouteImport } from './routes/sorteios.$id.index'
import { Route as SorteiosIdCuponsRouteImport } from './routes/sorteios.$id.cupons'
import { Route as SorteiosIdEditarRouteImport } from './routes/sorteios.$id.editar'
import { Route as SorteiosIdNotasRouteImport } from './routes/sorteios.$id.notas'
import { Route as SorteiosIdParticipantesRouteImport } from './routes/sorteios.$id.participantes'
import { Route as SorteiosIdPremiosRouteImport } from './routes/sorteios.$id.premios'
import { Route as SorteiosIdTermosRouteImport } from './routes/sorteios.$id.termos'
import { Route as ApiPublicSorteiosReconciliarRouteImport } from './routes/api/public/sorteios/reconciliar'
import { Route as ApiPublicSorteiosValidarNotasRouteImport } from './routes/api/public/sorteios/validar-notas'
import { Route as ApiPublicWhatsappFilaRouteImport } from './routes/api/public/whatsapp/fila'
import { Route as ApiPublicWhatsappInatividadeRouteImport } from './routes/api/public/whatsapp/inatividade'
import { Route as ApiPublicWhatsappMidiaRouteImport } from './routes/api/public/whatsapp/midia'
import { Route as ApiPublicWhatsappStatusRouteImport } from './routes/api/public/whatsapp/status'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicSorteiosSyncClientesAlteracoesRouteImport } from './routes/api/public/sorteios/sync/clientes-alteracoes'
import { Route as ApiPublicSorteiosSyncClientesConfirmarRouteImport } from './routes/api/public/sorteios/sync/clientes-confirmar'
import { Route as ApiPublicSorteiosSyncClientesReceberRouteImport } from './routes/api/public/sorteios/sync/clientes-receber'
import { Route as ApiPublicSorteiosSyncNotasConfirmarRouteImport } from './routes/api/public/sorteios/sync/notas-confirmar'
import { Route as ApiPublicSorteiosSyncNotasLoteRouteImport } from './routes/api/public/sorteios/sync/notas-lote'
import { Route as ApiPublicSorteiosSyncNotasSituacaoRouteImport } from './routes/api/public/sorteios/sync/notas-situacao'
import { Route as ApiPublicWhatsappWebhookTokenRouteImport } from './routes/api/public/whatsapp/webhook/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoriasRoute = MelhoriasRouteImport.update({
  id: '/melhorias',
  path: '/melhorias',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRapidasRoute = MensagensRapidasRouteImport.update({
  id: '/mensagens-rapidas',
  path: '/mensagens-rapidas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculosIndexRoute = CurriculosIndexRouteImport.update({
  id: '/curriculos/',
  path: '/curriculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculosIdRoute = CurriculosIdRouteImport.update({
  id: '/curriculos/$id',
  path: '/curriculos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoTokenRoute = OrcamentoTokenRouteImport.update({
  id: '/orcamento/$token',
  path: '/orcamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosPublicoIndexRoute = SorteiosPublicoIndexRouteImport.update({
  id: '/sorteios-publico/',
  path: '/sorteios-publico/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosPublicoCadastroRoute = SorteiosPublicoCadastroRouteImport.update({
  id: '/sorteios-publico/cadastro',
  path: '/sorteios-publico/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosPublicoCuponsRoute = SorteiosPublicoCuponsRouteImport.update({
  id: '/sorteios-publico/cupons',
  path: '/sorteios-publico/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosPublicoInformacoesRoute =
  SorteiosPublicoInformacoesRouteImport.update({
    id: '/sorteios-publico/informacoes',
    path: '/sorteios-publico/informacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const SorteiosPublicoNotasRoute = SorteiosPublicoNotasRouteImport.update({
  id: '/sorteios-publico/notas',
  path: '/sorteios-publico/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosPublicoPainelRoute = SorteiosPublicoPainelRouteImport.update({
  id: '/sorteios-publico/painel',
  path: '/sorteios-publico/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosPublicoTelefoneRoute = SorteiosPublicoTelefoneRouteImport.update({
  id: '/sorteios-publico/telefone',
  path: '/sorteios-publico/telefone',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosPublicoTermosRoute = SorteiosPublicoTermosRouteImport.update({
  id: '/sorteios-publico/termos',
  path: '/sorteios-publico/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIndexRoute = SorteiosIndexRouteImport.update({
  id: '/sorteios/',
  path: '/sorteios/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosNovoRoute = SorteiosNovoRouteImport.update({
  id: '/sorteios/novo',
  path: '/sorteios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoPublicoTokenRoute = CurriculoPublicoTokenRouteImport.update({
  id: '/curriculo/publico/$token',
  path: '/curriculo/publico/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIdIndexRoute = SorteiosIdIndexRouteImport.update({
  id: '/sorteios/$id/',
  path: '/sorteios/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIdCuponsRoute = SorteiosIdCuponsRouteImport.update({
  id: '/sorteios/$id/cupons',
  path: '/sorteios/$id/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIdEditarRoute = SorteiosIdEditarRouteImport.update({
  id: '/sorteios/$id/editar',
  path: '/sorteios/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIdNotasRoute = SorteiosIdNotasRouteImport.update({
  id: '/sorteios/$id/notas',
  path: '/sorteios/$id/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIdParticipantesRoute = SorteiosIdParticipantesRouteImport.update({
  id: '/sorteios/$id/participantes',
  path: '/sorteios/$id/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIdPremiosRoute = SorteiosIdPremiosRouteImport.update({
  id: '/sorteios/$id/premios',
  path: '/sorteios/$id/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteiosIdTermosRoute = SorteiosIdTermosRouteImport.update({
  id: '/sorteios/$id/termos',
  path: '/sorteios/$id/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSorteiosReconciliarRoute =
  ApiPublicSorteiosReconciliarRouteImport.update({
    id: '/api/public/sorteios/reconciliar',
    path: '/api/public/sorteios/reconciliar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSorteiosValidarNotasRoute =
  ApiPublicSorteiosValidarNotasRouteImport.update({
    id: '/api/public/sorteios/validar-notas',
    path: '/api/public/sorteios/validar-notas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappFilaRoute = ApiPublicWhatsappFilaRouteImport.update({
  id: '/api/public/whatsapp/fila',
  path: '/api/public/whatsapp/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappInatividadeRoute =
  ApiPublicWhatsappInatividadeRouteImport.update({
    id: '/api/public/whatsapp/inatividade',
    path: '/api/public/whatsapp/inatividade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappMidiaRoute = ApiPublicWhatsappMidiaRouteImport.update({
  id: '/api/public/whatsapp/midia',
  path: '/api/public/whatsapp/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappStatusRoute = ApiPublicWhatsappStatusRouteImport.update({
  id: '/api/public/whatsapp/status',
  path: '/api/public/whatsapp/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSorteiosSyncClientesAlteracoesRoute =
  ApiPublicSorteiosSyncClientesAlteracoesRouteImport.update({
    id: '/api/public/sorteios/sync/clientes-alteracoes',
    path: '/api/public/sorteios/sync/clientes-alteracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSorteiosSyncClientesConfirmarRoute =
  ApiPublicSorteiosSyncClientesConfirmarRouteImport.update({
    id: '/api/public/sorteios/sync/clientes-confirmar',
    path: '/api/public/sorteios/sync/clientes-confirmar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSorteiosSyncClientesReceberRoute =
  ApiPublicSorteiosSyncClientesReceberRouteImport.update({
    id: '/api/public/sorteios/sync/clientes-receber',
    path: '/api/public/sorteios/sync/clientes-receber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSorteiosSyncNotasConfirmarRoute =
  ApiPublicSorteiosSyncNotasConfirmarRouteImport.update({
    id: '/api/public/sorteios/sync/notas-confirmar',
    path: '/api/public/sorteios/sync/notas-confirmar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSorteiosSyncNotasLoteRoute =
  ApiPublicSorteiosSyncNotasLoteRouteImport.update({
    id: '/api/public/sorteios/sync/notas-lote',
    path: '/api/public/sorteios/sync/notas-lote',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSorteiosSyncNotasSituacaoRoute =
  ApiPublicSorteiosSyncNotasSituacaoRouteImport.update({
    id: '/api/public/sorteios/sync/notas-situacao',
    path: '/api/public/sorteios/sync/notas-situacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookTokenRoute =
  ApiPublicWhatsappWebhookTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => ApiPublicWhatsappWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bot': typeof BotRoute
  '/clientes': typeof ClientesRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/melhorias': typeof MelhoriasRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/precos': typeof PrecosRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/curriculos/$id': typeof CurriculosIdRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/sorteios-publico/cadastro': typeof SorteiosPublicoCadastroRoute
  '/sorteios-publico/cupons': typeof SorteiosPublicoCuponsRoute
  '/sorteios-publico/informacoes': typeof SorteiosPublicoInformacoesRoute
  '/sorteios-publico/notas': typeof SorteiosPublicoNotasRoute
  '/sorteios-publico/painel': typeof SorteiosPublicoPainelRoute
  '/sorteios-publico/telefone': typeof SorteiosPublicoTelefoneRoute
  '/sorteios-publico/termos': typeof SorteiosPublicoTermosRoute
  '/sorteios/novo': typeof SorteiosNovoRoute
  '/curriculos/': typeof CurriculosIndexRoute
  '/sorteios-publico/': typeof SorteiosPublicoIndexRoute
  '/sorteios/': typeof SorteiosIndexRoute
  '/curriculo/publico/$token': typeof CurriculoPublicoTokenRoute
  '/sorteios/$id/cupons': typeof SorteiosIdCuponsRoute
  '/sorteios/$id/editar': typeof SorteiosIdEditarRoute
  '/sorteios/$id/notas': typeof SorteiosIdNotasRoute
  '/sorteios/$id/participantes': typeof SorteiosIdParticipantesRoute
  '/sorteios/$id/premios': typeof SorteiosIdPremiosRoute
  '/sorteios/$id/termos': typeof SorteiosIdTermosRoute
  '/sorteios/$id/': typeof SorteiosIdIndexRoute
  '/api/public/sorteios/reconciliar': typeof ApiPublicSorteiosReconciliarRoute
  '/api/public/sorteios/validar-notas': typeof ApiPublicSorteiosValidarNotasRoute
  '/api/public/whatsapp/fila': typeof ApiPublicWhatsappFilaRoute
  '/api/public/whatsapp/inatividade': typeof ApiPublicWhatsappInatividadeRoute
  '/api/public/whatsapp/midia': typeof ApiPublicWhatsappMidiaRoute
  '/api/public/whatsapp/status': typeof ApiPublicWhatsappStatusRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/sorteios/sync/clientes-alteracoes': typeof ApiPublicSorteiosSyncClientesAlteracoesRoute
  '/api/public/sorteios/sync/clientes-confirmar': typeof ApiPublicSorteiosSyncClientesConfirmarRoute
  '/api/public/sorteios/sync/clientes-receber': typeof ApiPublicSorteiosSyncClientesReceberRoute
  '/api/public/sorteios/sync/notas-confirmar': typeof ApiPublicSorteiosSyncNotasConfirmarRoute
  '/api/public/sorteios/sync/notas-lote': typeof ApiPublicSorteiosSyncNotasLoteRoute
  '/api/public/sorteios/sync/notas-situacao': typeof ApiPublicSorteiosSyncNotasSituacaoRoute
  '/api/public/whatsapp/webhook/$token': typeof ApiPublicWhatsappWebhookTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bot': typeof BotRoute
  '/clientes': typeof ClientesRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/melhorias': typeof MelhoriasRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/precos': typeof PrecosRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/curriculos/$id': typeof CurriculosIdRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/sorteios-publico/cadastro': typeof SorteiosPublicoCadastroRoute
  '/sorteios-publico/cupons': typeof SorteiosPublicoCuponsRoute
  '/sorteios-publico/informacoes': typeof SorteiosPublicoInformacoesRoute
  '/sorteios-publico/notas': typeof SorteiosPublicoNotasRoute
  '/sorteios-publico/painel': typeof SorteiosPublicoPainelRoute
  '/sorteios-publico/telefone': typeof SorteiosPublicoTelefoneRoute
  '/sorteios-publico/termos': typeof SorteiosPublicoTermosRoute
  '/sorteios/novo': typeof SorteiosNovoRoute
  '/curriculos': typeof CurriculosIndexRoute
  '/sorteios-publico': typeof SorteiosPublicoIndexRoute
  '/sorteios': typeof SorteiosIndexRoute
  '/curriculo/publico/$token': typeof CurriculoPublicoTokenRoute
  '/sorteios/$id/cupons': typeof SorteiosIdCuponsRoute
  '/sorteios/$id/editar': typeof SorteiosIdEditarRoute
  '/sorteios/$id/notas': typeof SorteiosIdNotasRoute
  '/sorteios/$id/participantes': typeof SorteiosIdParticipantesRoute
  '/sorteios/$id/premios': typeof SorteiosIdPremiosRoute
  '/sorteios/$id/termos': typeof SorteiosIdTermosRoute
  '/sorteios/$id': typeof SorteiosIdIndexRoute
  '/api/public/sorteios/reconciliar': typeof ApiPublicSorteiosReconciliarRoute
  '/api/public/sorteios/validar-notas': typeof ApiPublicSorteiosValidarNotasRoute
  '/api/public/whatsapp/fila': typeof ApiPublicWhatsappFilaRoute
  '/api/public/whatsapp/inatividade': typeof ApiPublicWhatsappInatividadeRoute
  '/api/public/whatsapp/midia': typeof ApiPublicWhatsappMidiaRoute
  '/api/public/whatsapp/status': typeof ApiPublicWhatsappStatusRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/sorteios/sync/clientes-alteracoes': typeof ApiPublicSorteiosSyncClientesAlteracoesRoute
  '/api/public/sorteios/sync/clientes-confirmar': typeof ApiPublicSorteiosSyncClientesConfirmarRoute
  '/api/public/sorteios/sync/clientes-receber': typeof ApiPublicSorteiosSyncClientesReceberRoute
  '/api/public/sorteios/sync/notas-confirmar': typeof ApiPublicSorteiosSyncNotasConfirmarRoute
  '/api/public/sorteios/sync/notas-lote': typeof ApiPublicSorteiosSyncNotasLoteRoute
  '/api/public/sorteios/sync/notas-situacao': typeof ApiPublicSorteiosSyncNotasSituacaoRoute
  '/api/public/whatsapp/webhook/$token': typeof ApiPublicWhatsappWebhookTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bot': typeof BotRoute
  '/clientes': typeof ClientesRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/melhorias': typeof MelhoriasRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/precos': typeof PrecosRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/curriculos/$id': typeof CurriculosIdRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/sorteios-publico/cadastro': typeof SorteiosPublicoCadastroRoute
  '/sorteios-publico/cupons': typeof SorteiosPublicoCuponsRoute
  '/sorteios-publico/informacoes': typeof SorteiosPublicoInformacoesRoute
  '/sorteios-publico/notas': typeof SorteiosPublicoNotasRoute
  '/sorteios-publico/painel': typeof SorteiosPublicoPainelRoute
  '/sorteios-publico/telefone': typeof SorteiosPublicoTelefoneRoute
  '/sorteios-publico/termos': typeof SorteiosPublicoTermosRoute
  '/sorteios/novo': typeof SorteiosNovoRoute
  '/curriculos/': typeof CurriculosIndexRoute
  '/sorteios-publico/': typeof SorteiosPublicoIndexRoute
  '/sorteios/': typeof SorteiosIndexRoute
  '/curriculo/publico/$token': typeof CurriculoPublicoTokenRoute
  '/sorteios/$id/cupons': typeof SorteiosIdCuponsRoute
  '/sorteios/$id/editar': typeof SorteiosIdEditarRoute
  '/sorteios/$id/notas': typeof SorteiosIdNotasRoute
  '/sorteios/$id/participantes': typeof SorteiosIdParticipantesRoute
  '/sorteios/$id/premios': typeof SorteiosIdPremiosRoute
  '/sorteios/$id/termos': typeof SorteiosIdTermosRoute
  '/sorteios/$id/': typeof SorteiosIdIndexRoute
  '/api/public/sorteios/reconciliar': typeof ApiPublicSorteiosReconciliarRoute
  '/api/public/sorteios/validar-notas': typeof ApiPublicSorteiosValidarNotasRoute
  '/api/public/whatsapp/fila': typeof ApiPublicWhatsappFilaRoute
  '/api/public/whatsapp/inatividade': typeof ApiPublicWhatsappInatividadeRoute
  '/api/public/whatsapp/midia': typeof ApiPublicWhatsappMidiaRoute
  '/api/public/whatsapp/status': typeof ApiPublicWhatsappStatusRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/sorteios/sync/clientes-alteracoes': typeof ApiPublicSorteiosSyncClientesAlteracoesRoute
  '/api/public/sorteios/sync/clientes-confirmar': typeof ApiPublicSorteiosSyncClientesConfirmarRoute
  '/api/public/sorteios/sync/clientes-receber': typeof ApiPublicSorteiosSyncClientesReceberRoute
  '/api/public/sorteios/sync/notas-confirmar': typeof ApiPublicSorteiosSyncNotasConfirmarRoute
  '/api/public/sorteios/sync/notas-lote': typeof ApiPublicSorteiosSyncNotasLoteRoute
  '/api/public/sorteios/sync/notas-situacao': typeof ApiPublicSorteiosSyncNotasSituacaoRoute
  '/api/public/whatsapp/webhook/$token': typeof ApiPublicWhatsappWebhookTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bot'
    | '/clientes'
    | '/conexoes'
    | '/configuracoes'
    | '/dashboard'
    | '/melhorias'
    | '/mensagens-rapidas'
    | '/orcamentos'
    | '/precos'
    | '/usuarios'
    | '/whatsapp'
    | '/curriculos/$id'
    | '/orcamento/$token'
    | '/sorteios-publico/cadastro'
    | '/sorteios-publico/cupons'
    | '/sorteios-publico/informacoes'
    | '/sorteios-publico/notas'
    | '/sorteios-publico/painel'
    | '/sorteios-publico/telefone'
    | '/sorteios-publico/termos'
    | '/sorteios/novo'
    | '/curriculos/'
    | '/sorteios-publico/'
    | '/sorteios/'
    | '/curriculo/publico/$token'
    | '/sorteios/$id/cupons'
    | '/sorteios/$id/editar'
    | '/sorteios/$id/notas'
    | '/sorteios/$id/participantes'
    | '/sorteios/$id/premios'
    | '/sorteios/$id/termos'
    | '/sorteios/$id/'
    | '/api/public/sorteios/reconciliar'
    | '/api/public/sorteios/validar-notas'
    | '/api/public/whatsapp/fila'
    | '/api/public/whatsapp/inatividade'
    | '/api/public/whatsapp/midia'
    | '/api/public/whatsapp/status'
    | '/api/public/whatsapp/webhook'
    | '/api/public/sorteios/sync/clientes-alteracoes'
    | '/api/public/sorteios/sync/clientes-confirmar'
    | '/api/public/sorteios/sync/clientes-receber'
    | '/api/public/sorteios/sync/notas-confirmar'
    | '/api/public/sorteios/sync/notas-lote'
    | '/api/public/sorteios/sync/notas-situacao'
    | '/api/public/whatsapp/webhook/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bot'
    | '/clientes'
    | '/conexoes'
    | '/configuracoes'
    | '/dashboard'
    | '/melhorias'
    | '/mensagens-rapidas'
    | '/orcamentos'
    | '/precos'
    | '/usuarios'
    | '/whatsapp'
    | '/curriculos/$id'
    | '/orcamento/$token'
    | '/sorteios-publico/cadastro'
    | '/sorteios-publico/cupons'
    | '/sorteios-publico/informacoes'
    | '/sorteios-publico/notas'
    | '/sorteios-publico/painel'
    | '/sorteios-publico/telefone'
    | '/sorteios-publico/termos'
    | '/sorteios/novo'
    | '/curriculos'
    | '/sorteios-publico'
    | '/sorteios'
    | '/curriculo/publico/$token'
    | '/sorteios/$id/cupons'
    | '/sorteios/$id/editar'
    | '/sorteios/$id/notas'
    | '/sorteios/$id/participantes'
    | '/sorteios/$id/premios'
    | '/sorteios/$id/termos'
    | '/sorteios/$id'
    | '/api/public/sorteios/reconciliar'
    | '/api/public/sorteios/validar-notas'
    | '/api/public/whatsapp/fila'
    | '/api/public/whatsapp/inatividade'
    | '/api/public/whatsapp/midia'
    | '/api/public/whatsapp/status'
    | '/api/public/whatsapp/webhook'
    | '/api/public/sorteios/sync/clientes-alteracoes'
    | '/api/public/sorteios/sync/clientes-confirmar'
    | '/api/public/sorteios/sync/clientes-receber'
    | '/api/public/sorteios/sync/notas-confirmar'
    | '/api/public/sorteios/sync/notas-lote'
    | '/api/public/sorteios/sync/notas-situacao'
    | '/api/public/whatsapp/webhook/$token'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bot'
    | '/clientes'
    | '/conexoes'
    | '/configuracoes'
    | '/dashboard'
    | '/melhorias'
    | '/mensagens-rapidas'
    | '/orcamentos'
    | '/precos'
    | '/usuarios'
    | '/whatsapp'
    | '/curriculos/$id'
    | '/orcamento/$token'
    | '/sorteios-publico/cadastro'
    | '/sorteios-publico/cupons'
    | '/sorteios-publico/informacoes'
    | '/sorteios-publico/notas'
    | '/sorteios-publico/painel'
    | '/sorteios-publico/telefone'
    | '/sorteios-publico/termos'
    | '/sorteios/novo'
    | '/curriculos/'
    | '/sorteios-publico/'
    | '/sorteios/'
    | '/curriculo/publico/$token'
    | '/sorteios/$id/cupons'
    | '/sorteios/$id/editar'
    | '/sorteios/$id/notas'
    | '/sorteios/$id/participantes'
    | '/sorteios/$id/premios'
    | '/sorteios/$id/termos'
    | '/sorteios/$id/'
    | '/api/public/sorteios/reconciliar'
    | '/api/public/sorteios/validar-notas'
    | '/api/public/whatsapp/fila'
    | '/api/public/whatsapp/inatividade'
    | '/api/public/whatsapp/midia'
    | '/api/public/whatsapp/status'
    | '/api/public/whatsapp/webhook'
    | '/api/public/sorteios/sync/clientes-alteracoes'
    | '/api/public/sorteios/sync/clientes-confirmar'
    | '/api/public/sorteios/sync/clientes-receber'
    | '/api/public/sorteios/sync/notas-confirmar'
    | '/api/public/sorteios/sync/notas-lote'
    | '/api/public/sorteios/sync/notas-situacao'
    | '/api/public/whatsapp/webhook/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BotRoute: typeof BotRoute
  ClientesRoute: typeof ClientesRoute
  ConexoesRoute: typeof ConexoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  MelhoriasRoute: typeof MelhoriasRoute
  MensagensRapidasRoute: typeof MensagensRapidasRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PrecosRoute: typeof PrecosRoute
  UsuariosRoute: typeof UsuariosRoute
  WhatsappRoute: typeof WhatsappRoute
  CurriculosIdRoute: typeof CurriculosIdRoute
  OrcamentoTokenRoute: typeof OrcamentoTokenRoute
  SorteiosPublicoCadastroRoute: typeof SorteiosPublicoCadastroRoute
  SorteiosPublicoCuponsRoute: typeof SorteiosPublicoCuponsRoute
  SorteiosPublicoInformacoesRoute: typeof SorteiosPublicoInformacoesRoute
  SorteiosPublicoNotasRoute: typeof SorteiosPublicoNotasRoute
  SorteiosPublicoPainelRoute: typeof SorteiosPublicoPainelRoute
  SorteiosPublicoTelefoneRoute: typeof SorteiosPublicoTelefoneRoute
  SorteiosPublicoTermosRoute: typeof SorteiosPublicoTermosRoute
  SorteiosNovoRoute: typeof SorteiosNovoRoute
  CurriculosIndexRoute: typeof CurriculosIndexRoute
  SorteiosPublicoIndexRoute: typeof SorteiosPublicoIndexRoute
  SorteiosIndexRoute: typeof SorteiosIndexRoute
  CurriculoPublicoTokenRoute: typeof CurriculoPublicoTokenRoute
  SorteiosIdCuponsRoute: typeof SorteiosIdCuponsRoute
  SorteiosIdEditarRoute: typeof SorteiosIdEditarRoute
  SorteiosIdNotasRoute: typeof SorteiosIdNotasRoute
  SorteiosIdParticipantesRoute: typeof SorteiosIdParticipantesRoute
  SorteiosIdPremiosRoute: typeof SorteiosIdPremiosRoute
  SorteiosIdTermosRoute: typeof SorteiosIdTermosRoute
  SorteiosIdIndexRoute: typeof SorteiosIdIndexRoute
  ApiPublicSorteiosReconciliarRoute: typeof ApiPublicSorteiosReconciliarRoute
  ApiPublicSorteiosValidarNotasRoute: typeof ApiPublicSorteiosValidarNotasRoute
  ApiPublicWhatsappFilaRoute: typeof ApiPublicWhatsappFilaRoute
  ApiPublicWhatsappInatividadeRoute: typeof ApiPublicWhatsappInatividadeRoute
  ApiPublicWhatsappMidiaRoute: typeof ApiPublicWhatsappMidiaRoute
  ApiPublicWhatsappStatusRoute: typeof ApiPublicWhatsappStatusRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRouteWithChildren
  ApiPublicSorteiosSyncClientesAlteracoesRoute: typeof ApiPublicSorteiosSyncClientesAlteracoesRoute
  ApiPublicSorteiosSyncClientesConfirmarRoute: typeof ApiPublicSorteiosSyncClientesConfirmarRoute
  ApiPublicSorteiosSyncClientesReceberRoute: typeof ApiPublicSorteiosSyncClientesReceberRoute
  ApiPublicSorteiosSyncNotasConfirmarRoute: typeof ApiPublicSorteiosSyncNotasConfirmarRoute
  ApiPublicSorteiosSyncNotasLoteRoute: typeof ApiPublicSorteiosSyncNotasLoteRoute
  ApiPublicSorteiosSyncNotasSituacaoRoute: typeof ApiPublicSorteiosSyncNotasSituacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhorias': {
      id: '/melhorias'
      path: '/melhorias'
      fullPath: '/melhorias'
      preLoaderRoute: typeof MelhoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens-rapidas': {
      id: '/mensagens-rapidas'
      path: '/mensagens-rapidas'
      fullPath: '/mensagens-rapidas'
      preLoaderRoute: typeof MensagensRapidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculos/': {
      id: '/curriculos/'
      path: '/curriculos'
      fullPath: '/curriculos/'
      preLoaderRoute: typeof CurriculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculos/$id': {
      id: '/curriculos/$id'
      path: '/curriculos/$id'
      fullPath: '/curriculos/$id'
      preLoaderRoute: typeof CurriculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento/$token': {
      id: '/orcamento/$token'
      path: '/orcamento/$token'
      fullPath: '/orcamento/$token'
      preLoaderRoute: typeof OrcamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/': {
      id: '/sorteios-publico/'
      path: '/sorteios-publico'
      fullPath: '/sorteios-publico/'
      preLoaderRoute: typeof SorteiosPublicoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/cadastro': {
      id: '/sorteios-publico/cadastro'
      path: '/sorteios-publico/cadastro'
      fullPath: '/sorteios-publico/cadastro'
      preLoaderRoute: typeof SorteiosPublicoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/cupons': {
      id: '/sorteios-publico/cupons'
      path: '/sorteios-publico/cupons'
      fullPath: '/sorteios-publico/cupons'
      preLoaderRoute: typeof SorteiosPublicoCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/informacoes': {
      id: '/sorteios-publico/informacoes'
      path: '/sorteios-publico/informacoes'
      fullPath: '/sorteios-publico/informacoes'
      preLoaderRoute: typeof SorteiosPublicoInformacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/notas': {
      id: '/sorteios-publico/notas'
      path: '/sorteios-publico/notas'
      fullPath: '/sorteios-publico/notas'
      preLoaderRoute: typeof SorteiosPublicoNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/painel': {
      id: '/sorteios-publico/painel'
      path: '/sorteios-publico/painel'
      fullPath: '/sorteios-publico/painel'
      preLoaderRoute: typeof SorteiosPublicoPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/telefone': {
      id: '/sorteios-publico/telefone'
      path: '/sorteios-publico/telefone'
      fullPath: '/sorteios-publico/telefone'
      preLoaderRoute: typeof SorteiosPublicoTelefoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios-publico/termos': {
      id: '/sorteios-publico/termos'
      path: '/sorteios-publico/termos'
      fullPath: '/sorteios-publico/termos'
      preLoaderRoute: typeof SorteiosPublicoTermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/': {
      id: '/sorteios/'
      path: '/sorteios'
      fullPath: '/sorteios/'
      preLoaderRoute: typeof SorteiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/novo': {
      id: '/sorteios/novo'
      path: '/sorteios/novo'
      fullPath: '/sorteios/novo'
      preLoaderRoute: typeof SorteiosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo/publico/$token': {
      id: '/curriculo/publico/$token'
      path: '/curriculo/publico/$token'
      fullPath: '/curriculo/publico/$token'
      preLoaderRoute: typeof CurriculoPublicoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/$id/': {
      id: '/sorteios/$id/'
      path: '/sorteios/$id'
      fullPath: '/sorteios/$id/'
      preLoaderRoute: typeof SorteiosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/$id/cupons': {
      id: '/sorteios/$id/cupons'
      path: '/sorteios/$id/cupons'
      fullPath: '/sorteios/$id/cupons'
      preLoaderRoute: typeof SorteiosIdCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/$id/editar': {
      id: '/sorteios/$id/editar'
      path: '/sorteios/$id/editar'
      fullPath: '/sorteios/$id/editar'
      preLoaderRoute: typeof SorteiosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/$id/notas': {
      id: '/sorteios/$id/notas'
      path: '/sorteios/$id/notas'
      fullPath: '/sorteios/$id/notas'
      preLoaderRoute: typeof SorteiosIdNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/$id/participantes': {
      id: '/sorteios/$id/participantes'
      path: '/sorteios/$id/participantes'
      fullPath: '/sorteios/$id/participantes'
      preLoaderRoute: typeof SorteiosIdParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/$id/premios': {
      id: '/sorteios/$id/premios'
      path: '/sorteios/$id/premios'
      fullPath: '/sorteios/$id/premios'
      preLoaderRoute: typeof SorteiosIdPremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteios/$id/termos': {
      id: '/sorteios/$id/termos'
      path: '/sorteios/$id/termos'
      fullPath: '/sorteios/$id/termos'
      preLoaderRoute: typeof SorteiosIdTermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/reconciliar': {
      id: '/api/public/sorteios/reconciliar'
      path: '/api/public/sorteios/reconciliar'
      fullPath: '/api/public/sorteios/reconciliar'
      preLoaderRoute: typeof ApiPublicSorteiosReconciliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/validar-notas': {
      id: '/api/public/sorteios/validar-notas'
      path: '/api/public/sorteios/validar-notas'
      fullPath: '/api/public/sorteios/validar-notas'
      preLoaderRoute: typeof ApiPublicSorteiosValidarNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/fila': {
      id: '/api/public/whatsapp/fila'
      path: '/api/public/whatsapp/fila'
      fullPath: '/api/public/whatsapp/fila'
      preLoaderRoute: typeof ApiPublicWhatsappFilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/inatividade': {
      id: '/api/public/whatsapp/inatividade'
      path: '/api/public/whatsapp/inatividade'
      fullPath: '/api/public/whatsapp/inatividade'
      preLoaderRoute: typeof ApiPublicWhatsappInatividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/midia': {
      id: '/api/public/whatsapp/midia'
      path: '/api/public/whatsapp/midia'
      fullPath: '/api/public/whatsapp/midia'
      preLoaderRoute: typeof ApiPublicWhatsappMidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/status': {
      id: '/api/public/whatsapp/status'
      path: '/api/public/whatsapp/status'
      fullPath: '/api/public/whatsapp/status'
      preLoaderRoute: typeof ApiPublicWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/sync/clientes-alteracoes': {
      id: '/api/public/sorteios/sync/clientes-alteracoes'
      path: '/api/public/sorteios/sync/clientes-alteracoes'
      fullPath: '/api/public/sorteios/sync/clientes-alteracoes'
      preLoaderRoute: typeof ApiPublicSorteiosSyncClientesAlteracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/sync/clientes-confirmar': {
      id: '/api/public/sorteios/sync/clientes-confirmar'
      path: '/api/public/sorteios/sync/clientes-confirmar'
      fullPath: '/api/public/sorteios/sync/clientes-confirmar'
      preLoaderRoute: typeof ApiPublicSorteiosSyncClientesConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/sync/clientes-receber': {
      id: '/api/public/sorteios/sync/clientes-receber'
      path: '/api/public/sorteios/sync/clientes-receber'
      fullPath: '/api/public/sorteios/sync/clientes-receber'
      preLoaderRoute: typeof ApiPublicSorteiosSyncClientesReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/sync/notas-confirmar': {
      id: '/api/public/sorteios/sync/notas-confirmar'
      path: '/api/public/sorteios/sync/notas-confirmar'
      fullPath: '/api/public/sorteios/sync/notas-confirmar'
      preLoaderRoute: typeof ApiPublicSorteiosSyncNotasConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/sync/notas-lote': {
      id: '/api/public/sorteios/sync/notas-lote'
      path: '/api/public/sorteios/sync/notas-lote'
      fullPath: '/api/public/sorteios/sync/notas-lote'
      preLoaderRoute: typeof ApiPublicSorteiosSyncNotasLoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sorteios/sync/notas-situacao': {
      id: '/api/public/sorteios/sync/notas-situacao'
      path: '/api/public/sorteios/sync/notas-situacao'
      fullPath: '/api/public/sorteios/sync/notas-situacao'
      preLoaderRoute: typeof ApiPublicSorteiosSyncNotasSituacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook/$token': {
      id: '/api/public/whatsapp/webhook/$token'
      path: '/$token'
      fullPath: '/api/public/whatsapp/webhook/$token'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookTokenRouteImport
      parentRoute: typeof ApiPublicWhatsappWebhookRoute
    }
  }
}

interface ApiPublicWhatsappWebhookRouteChildren {
  ApiPublicWhatsappWebhookTokenRoute: typeof ApiPublicWhatsappWebhookTokenRoute
}

const ApiPublicWhatsappWebhookRouteChildren: ApiPublicWhatsappWebhookRouteChildren =
  {
    ApiPublicWhatsappWebhookTokenRoute: ApiPublicWhatsappWebhookTokenRoute,
  }

const ApiPublicWhatsappWebhookRouteWithChildren =
  ApiPublicWhatsappWebhookRoute._addFileChildren(
    ApiPublicWhatsappWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BotRoute: BotRoute,
  ClientesRoute: ClientesRoute,
  ConexoesRoute: ConexoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  MelhoriasRoute: MelhoriasRoute,
  MensagensRapidasRoute: MensagensRapidasRoute,
  OrcamentosRoute: OrcamentosRoute,
  PrecosRoute: PrecosRoute,
  UsuariosRoute: UsuariosRoute,
  WhatsappRoute: WhatsappRoute,
  CurriculosIdRoute: CurriculosIdRoute,
  OrcamentoTokenRoute: OrcamentoTokenRoute,
  SorteiosPublicoCadastroRoute: SorteiosPublicoCadastroRoute,
  SorteiosPublicoCuponsRoute: SorteiosPublicoCuponsRoute,
  SorteiosPublicoInformacoesRoute: SorteiosPublicoInformacoesRoute,
  SorteiosPublicoNotasRoute: SorteiosPublicoNotasRoute,
  SorteiosPublicoPainelRoute: SorteiosPublicoPainelRoute,
  SorteiosPublicoTelefoneRoute: SorteiosPublicoTelefoneRoute,
  SorteiosPublicoTermosRoute: SorteiosPublicoTermosRoute,
  SorteiosNovoRoute: SorteiosNovoRoute,
  CurriculosIndexRoute: CurriculosIndexRoute,
  SorteiosPublicoIndexRoute: SorteiosPublicoIndexRoute,
  SorteiosIndexRoute: SorteiosIndexRoute,
  CurriculoPublicoTokenRoute: CurriculoPublicoTokenRoute,
  SorteiosIdCuponsRoute: SorteiosIdCuponsRoute,
  SorteiosIdEditarRoute: SorteiosIdEditarRoute,
  SorteiosIdNotasRoute: SorteiosIdNotasRoute,
  SorteiosIdParticipantesRoute: SorteiosIdParticipantesRoute,
  SorteiosIdPremiosRoute: SorteiosIdPremiosRoute,
  SorteiosIdTermosRoute: SorteiosIdTermosRoute,
  SorteiosIdIndexRoute: SorteiosIdIndexRoute,
  ApiPublicSorteiosReconciliarRoute: ApiPublicSorteiosReconciliarRoute,
  ApiPublicSorteiosValidarNotasRoute: ApiPublicSorteiosValidarNotasRoute,
  ApiPublicWhatsappFilaRoute: ApiPublicWhatsappFilaRoute,
  ApiPublicWhatsappInatividadeRoute: ApiPublicWhatsappInatividadeRoute,
  ApiPublicWhatsappMidiaRoute: ApiPublicWhatsappMidiaRoute,
  ApiPublicWhatsappStatusRoute: ApiPublicWhatsappStatusRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRouteWithChildren,
  ApiPublicSorteiosSyncClientesAlteracoesRoute:
    ApiPublicSorteiosSyncClientesAlteracoesRoute,
  ApiPublicSorteiosSyncClientesConfirmarRoute:
    ApiPublicSorteiosSyncClientesConfirmarRoute,
  ApiPublicSorteiosSyncClientesReceberRoute:
    ApiPublicSorteiosSyncClientesReceberRoute,
  ApiPublicSorteiosSyncNotasConfirmarRoute:
    ApiPublicSorteiosSyncNotasConfirmarRoute,
  ApiPublicSorteiosSyncNotasLoteRoute: ApiPublicSorteiosSyncNotasLoteRoute,
  ApiPublicSorteiosSyncNotasSituacaoRoute:
    ApiPublicSorteiosSyncNotasSituacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
